export const copy = {
  meta: {
    title: "证据审阅平台原型 | Evidence Review Platform Prototype",
    prototype: "交互原型 / Interactive prototype",
    synthetic: "演示数据 / Synthetic data",
    version: "v0.7 · 2026-09-29",
  },
  brand: {
    mark: "T",
    name: "Relativity 中文原型 / Chinese Prototype",
    shortName: "Relativity 原型 / Prototype",
  },
  workspace: {
    client: "Close AI Ltd.",
    matter: "高管马克欺诈项目调查 / Project Mark Fraud",
    name: "马克欺诈项目工作区 / MF Workspace",
    switchLabel: "切换工作区 / Switch workspace",
    allWorkspaces: "所有工作区 / All workspaces",
    role: "工作区管理员 / Workspace admin",
    user: "林然 / Ran Lin",
  },
  common: {
    priorityP0: "P0 核心 / Core",
    priorityP1: "P1 闭环 / Completion",
    featureIds: "功能 ID / Feature IDs",
    scope: "范围追溯 / Scope trace",
    search: "搜索 / Search",
    clear: "清除 / Clear",
    cancel: "取消 / Cancel",
    close: "关闭 / Close",
    confirm: "确认 / Confirm",
    save: "保存 / Save",
    saveNext: "保存并下一份 / Save & Next",
    edit: "编辑 / Edit",
    retry: "重试 / Retry",
    download: "下载 / Download",
    export: "导出 / Export",
    view: "查看 / View",
    continue: "继续 / Continue",
    back: "返回 / Back",
    next: "下一步 / Next",
    run: "运行 / Run",
    new: "新建 / New",
    create: "创建 / Create",
    refresh: "刷新 / Refresh",
    more: "更多 / More",
    selected: "已选择 / Selected",
    total: "总计 / Total",
    completed: "已完成 / Completed",
    inProgress: "进行中 / In progress",
    waiting: "等待中 / Waiting",
    failed: "失败 / Failed",
    partial: "部分完成 / Partial",
    ready: "就绪 / Ready",
    draft: "草稿 / Draft",
    active: "活动 / Active",
    all: "全部 / All",
    settings: "设置 / Settings",
    openMenu: "打开菜单 / Open menu",
    collapse: "收起 / Collapse",
    expand: "展开 / Expand",
    previous: "上一项 / Previous",
    nextItem: "下一项 / Next",
    firstPage: "第一页 / First page",
    previousPage: "上一页 / Previous page",
    nextPage: "下一页 / Next page",
    lastPage: "最后一页 / Last page",
    rowsPerPage: "每页 25 条 / 25 per page",
    paginationRange: "1–25",
    paginationTotal: "/ 127",
    demoOnly: "仅用于流程演示，不代表真实租户配置 / For workflow demonstration only; not a live tenant configuration",
    unavailable: "暂不可用 / Unavailable",
    open: "打开 / Open",
    details: "详情 / Details",
    notifications: "通知 / Notifications",
    help: "帮助 / Help",
    userOptions: "用户选项 / User options",
    openImport: "打开导入 / Open import",
  },
  navigation: [
    { id: "audit", label: "审计 / Audit", short: "审计\nAudit" },
    { id: "reviewSetup", label: "审阅配置 / Review Setup", short: "审阅配置\nReview Setup" },
    { id: "other", label: "其他 / Other", short: "其他\nOther" },
    { id: "batches", label: "审阅批次 / Review Batches", short: "审阅批次\nReview Batches" },
    { id: "workspaces", label: "工作区 / Workspaces", short: "工作区\nWorkspaces" },
    { id: "users", label: "用户与组管理 / User and Group Management", short: "用户与组\nUsers & Groups" },
    { id: "fields", label: "字段与布局 / Fields & Layouts", short: "字段与布局\nFields & Layouts" },
    { id: "home", label: "概览 / Overview", short: "概览\nOverview" },
    { id: "processing", label: "处理 / Processing", short: "处理\nProcessing" },
    { id: "documents", label: "文档 / Documents", short: "文档\nDocuments" },
    { id: "analytics", label: "搜索与分析 / Search & Analytics", short: "搜索与分析\nSearch & Analytics" },
    { id: "review", label: "审阅 / Review", short: "审阅\nReview" },
    { id: "redaction", label: "成像与遮盖 / Imaging & Redact", short: "遮盖\nRedact" },
    { id: "production", label: "制作与导出 / Production & Export", short: "制作\nProduction" },
    { id: "tasks", label: "任务中心 / Task Center", short: "任务\nTasks" },
  ],
  access: {
    title: "证据审阅平台 / Evidence Review Platform",
    intro: "从工作区管理到证据审阅，按角色进入你的工作。 / Enter your workspace and review workflow with the right role.",
    flow: "选择身份 → 选择工作区 → 开始工作 / Choose role → Choose workspace → Start work",
    login: "登录 / Sign in", chooseRole: "选择演示身份 / Choose a demo role", account: "演示账户 / Demo account",
    enter: "登录并继续 / Sign in & continue", signOut: "退出登录 / Sign out",
    demo: "演示登录，无需密码；不连接真实账户。 / Demo sign-in, no password required; no live accounts connected.",
    roles: { admin: "管理员 / Administrator", reviewer: "用户／律师 / User / Lawyer" },
    roleDescriptions: { admin: "管理用户、工作区与完整案件流程 / Manage users, workspaces and case workflows", reviewer: "选择工作区、审阅文档与批次 / Choose workspaces and review documents and batches" },
    accounts: { admin: { id: "demo-admin", name: "林然 / Ran Lin" }, reviewer: { id: "demo-lawyer", name: "陈悦 / Yue Chen" } },
    platform: "平台管理 / Platform Administration", selection: "选择工作区 / Select workspace",
    selectHint: "选择一个工作区进入文档审阅。 / Choose a workspace to begin document review.",
    leave: "返回工作区列表 / Back to workspaces", denied: "当前身份或工作区范围无法访问此页面。 / This page is not available for the current role or workspace scope.",
    workspaceScope: "当前工作区 / Current workspace", platformScope: "工作区外 / Outside workspace",
    demoData: "以下为工作区流程的演示数据。 / The following data demonstrates the workspace workflow.",
  },
  modules: {
    reviewSetup: "审阅配置 / Review Setup", setupHint: "配置本工作区的字段、布局和高亮。 / Configure fields, layouts and highlights for this workspace.",
    highlights: "高亮 / Highlights", highlightName: "高亮名称 / Highlight name", terms: "关键词（每行一个） / Terms (one per line)",
    highlightDefault: "重点条款 / Key terms", highlightTerms: "termination\nagreement",
    highlightHint: "当前工作区的高亮词应用于文档审阅正文。 / Workspace highlight terms apply to document review text.",
    highlightSaved: "高亮已保存 / Highlights saved", enabled: "启用高亮 / Enable highlights",
    other: "其他 / Other", otherHint: "工作区辅助功能 / Workspace utilities", platformOtherHint: "平台辅助功能 / Platform utilities",
    dtsearch: "全文索引 / dtSearch Index", report: "搜索词报告 / Search Term Report", legacyAnalytics: "其他分析 / Other Analytics",
    reportHint: "以现有演示文档的文件名匹配展示报告流程；命中数不代表全文索引结果。 / Demonstrates the report flow using sample file names; counts are not full-text index results.",
    reportColumns: ["搜索词 / Search term", "命中文档 / Matching documents", "操作 / Action"], reportEmpty: "输入搜索词后运行报告。 / Enter terms and run the report.",
    reportTerms: "termination\nagreement\npricing", noMatches: "无匹配结果 / No matching results",
    foldersHint: "演示文件夹 / Demo folders", savedEmpty: "尚无已保存搜索 / No saved searches", invalidSearch: "请输入搜索名称。 / Enter a search name.",
    results: "演示文档数 / Sample documents", batchTitle: "审阅批次 / Review Batches",
    batchHint: "保留批次领取和进入原有审阅器的基础流程。 / Basic batch checkout and access to the existing viewer.",
    batchName: "一审批次 01 / First Pass Batch 01", batchColumns: ["批次 / Batch", "状态 / Status", "审阅人 / Reviewer", "操作 / Action"],
    checkout: "领取批次 / Check out", checkedOut: "已领取 / Checked out", release: "归还批次 / Check in", openBatch: "开始审阅 / Start review", unassigned: "未分配 / Unassigned", backDocuments: "返回文档 / Back to documents", backBatches: "返回批次 / Back to batches",
  },
  userStatus: {
    title: "用户状态 / User Status", hint: "查看用户当前会话、案件、客户和 Web 服务器信息。 / View each user’s current session, case, client, and web server details.",
    columns: ["用户名称 / User Name", "电子邮箱 / Email Address", "当前案件 / Current Case", "客户名称 / Client Name", "Web 服务器 / Web Server", "最后更新 / Last Update"],
    filters: ["筛选 / Filter", "筛选 / Filter", "筛选 / Filter", "筛选 / Filter", "筛选 / Filter", "(全部) / (All)"],
    currentAccounts: { admin: { email: "ran.lin@example.com", currentCase: "Project Mark Fraud", clientName: "Close AI Ltd.", webServer: "Web 服务器 01 / relativity-web-01", lastUpdate: "2026-09-30 09:45" }, reviewer: { email: "yue.chen@example.com", currentCase: "Project Mark Fraud", clientName: "Close AI Ltd.", webServer: "Web 服务器 01 / relativity-web-01", lastUpdate: "2026-09-30 09:45" } },
    online: "在线 / Online", current: "当前会话 / Current session", sample: "演示会话 / Sample session", offline: "离线 / Offline", account: "已创建账户 / Created account",
    samples: [
      { id: "demo-zhou", name: "周宁 / Ning Zhou", email: "ning.zhou@example.com", currentCase: "Project Mark Fraud", clientName: "Close AI Ltd.", webServer: "Web 服务器 01 / relativity-web-01", lastUpdate: "2026-09-30 09:42" },
      { id: "demo-wang", name: "王岚 / Lan Wang", email: "lan.wang@example.com", currentCase: "ARK Industries vs. Dknight Enterprises", clientName: "ARK Industries", webServer: "Web 服务器 02 / relativity-web-02", lastUpdate: "2026-09-30 09:38" },
    ],
    filterLabels: ["用户名称 / User Name", "电子邮箱 / Email Address", "当前案件 / Current Case", "客户名称 / Client Name", "Web 服务器 / Web Server", "最后更新 / Last Update"],
    unassigned: "未分配 / Unassigned",
  },
  audit: {
    title: "审计 / Audit", hint: "记录本次演示中的登录、工作区进出及页面操作反馈；刷新后重置。 / Tracks sign-ins, workspace entry/exit and action feedback in this demo; resets on refresh.",
    columns: ["时间 / Time", "用户 / User", "操作 / Action", "工作区 / Workspace"],
    login: "登录 / Signed in", logout: "退出登录 / Signed out", enter: "进入工作区 / Entered workspace", leave: "离开工作区 / Left workspace",
    empty: "暂无匹配记录 / No matching records", filter: "筛选审计记录 / Filter audit records", all: "全部工作区 / All workspaces",
  },
  fieldManagement: {
    title: "字段与布局 / Fields & Layouts",
    subtitle: "工作区设置 / Workspace Setup",
    ids: "Fields · Choices · Field Categories · Layouts",
    layouts: "布局 / Layouts",
    fields: "字段 / Fields", choices: "选项 / Choices", categories: "字段分类 / Field Categories",
    allFields: "全部字段 / All Fields", allCategories: "全部字段分类 / All Field Categories",
    newField: "新建字段 / New Field", newCategory: "新建字段分类 / New Field Category",
    fieldInformation: "字段信息 / Field Information", categoryDetails: "分类详情 / Category Details",
    objectType: "对象类型 / Object Type", document: "文档 / Document", fieldType: "字段类型 / Field Type",
    typeHint: "选择对象类型和字段类型以查看相关设置。 / Select an Object Type and Field Type to see relevant settings.",
    typeOptions: [
      { id: "currency", label: "货币 / Currency" }, { id: "date", label: "日期 / Date" },
      { id: "decimal", label: "小数 / Decimal" }, { id: "text", label: "定长文本 / Fixed-Length Text" },
      { id: "longText", label: "长文本 / Long Text" }, { id: "multiple", label: "多选 / Multiple Choice" },
      { id: "multipleObject", label: "多对象 / Multiple Object" }, { id: "single", label: "单选 / Single Choice" },
      { id: "singleObject", label: "单对象 / Single Object" }, { id: "boolean", label: "是／否 / Yes/No" },
    ],
    fieldSettings: "字段设置 / Field Settings", advancedSettings: "高级设置 / Advanced Settings",
    advancedUnavailable: "截图未展开此设置 / This setting is not shown in the reference screenshots",
    settings: [
      ["必填 / Required", "否 / No"],
      ["可用于字段树 / Available in Field Tree", "是 / Yes"],
      ["默认覆盖行为 / Default Overlay Behavior", "合并值 / Merge Values"],
    ],
    dashboard: "列表和仪表盘设置 / List and Dashboard Settings",
    dashboardSettings: [
      ["筛选类型 / Filter Type", "多选列表 / Multi-list"],
      ["启用排序／计数 / Enable Sort/Tally", "是 / Yes"],
      ["启用分组 / Enable Group By", "是 / Yes"],
      ["启用透视 / Enable Pivot", "是 / Yes"],
    ],
    addChoice: "添加选项 / Add Choice", addList: "批量添加选项 / Add List of Choices",
    addChild: "添加子选项 / Add Child Choice", choiceName: "选项名称 / Choice Name",
    choiceDetails: "选项详情 / Choice Details", parentChoice: "父选项 / Parent Choice",
    listHint: "每行输入一个选项 / Enter one choice per line",
    fillExamples: "填入截图中的选项 / Use choices from screenshots",
    exampleChoices: ["Fraud", "False Accounting", "Payments", "Procurement", "Payroll", "Trade", "Data Theft", "Intellectual Property"],
    reorder: "按名称排序 / Reorder A–Z", filterChoices: "筛选选项 / Filter choices",
    filterFields: "筛选字段 / Filter fields", filterCategories: "筛选字段分类 / Filter field categories",
    selectChoices: "选择全部选项 / Select all choices", selectFields: "选择全部字段 / Select all fields",
    autoSaved: "更改自动保存在当前会话 / Changes saved automatically in this session",
    deleteSelected: "删除所选 / Delete selected", deleteChoices: "删除选项 / Delete choices",
    deleteChoicesHint: "将删除所选选项及其全部子选项。 / Delete the selected choices and all their descendants.",
    order: "顺序 / Order", viewOrder: "查看顺序 / View Order", orderReference: "顺序参考 / Order Reference",
    orderHint: "数值越小越靠前；输入小于 10 的数值可排在默认分类之前。 / Lower values appear first; use a value below 10 to precede the default categories.",
    defaultOrder: 0,
    link: "关联 / Link", unlink: "取消关联 / Unlink", selectFieldsTitle: "选择字段 / Select Items - Fields",
    availableFields: "可用字段 / Available Fields", selectedFields: "已选字段 / Selected Fields",
    chooseField: "选择字段 / Select field", noChoiceField: "请先创建多选字段。 / Create a Multiple Choice field first.",
    fieldSaved: "字段已保存 / Field saved", categorySaved: "字段分类已保存 / Field category saved",
    choicesSaved: "选项已保存 / Choices saved", linked: "字段关联已保存 / Field links saved",
    unlinked: "字段已取消关联 / Fields unlinked", deleted: "记录已删除 / Record deleted",
    duplicateField: "同一对象下已存在同名字段。 / A field with this name already exists on this object.",
    duplicateCategory: "已存在同名字段分类。 / A field category with this name already exists.",
    duplicateChoice: "同一父选项下的名称不能重复。 / Choice names must be unique within the same parent.",
    choiceRequired: "请至少输入一个选项名称。 / Enter at least one choice name.",
    invalidOrder: "顺序必须是非负整数。 / Order must be a non-negative integer.",
    deleteTitle: "删除记录 / Delete record",
    deleteFieldHint: "将删除此字段及其选项，并移除分类中的关联。 / Delete this field and its choices, and remove its category links.",
    deleteCategoryHint: "将删除此分类；已关联的字段仍然保留。 / Delete this category; linked fields will be retained.",
    localOnly: "配置保留在当前浏览器会话中，刷新后恢复初始数据。 / Configuration is kept in this browser session; refreshing restores initial data.",
    actions: "操作 / Actions", separator: "：", branch: "└", empty: "—",
    columns: ["名称 / Name", "对象类型 / Object Type", "字段类型 / Field Type", "字段分类 / Field Categories"],
    categoryColumns: ["名称 / Name", "顺序 / Order", "字段 / Fields"],
    seedFields: [
      { id: "control-number", name: "Control Number", type: "text" },
      { id: "extracted-text", name: "Extracted Text", type: "longText" },
    ],
    seedCategories: [
      { id: "default", name: "Default Fields", order: 10, fieldIds: ["control-number", "extracted-text"] },
      { id: "email", name: "Email Fields", order: 20, fieldIds: [] },
      { id: "analytics", name: "Analytics Fields", order: 30, fieldIds: [] },
    ],
  },
  layoutManagement: {
    layouts: "布局 / Layouts",
    all: "全部布局 / All Layouts", new: "新建布局 / New Layout", information: "布局信息 / Layout Information",
    filter: "筛选布局 / Filter layouts", build: "构建布局 / Build Layout", editor: "编辑布局 / Edit Layout Information",
    copyPrevious: "启用复制上一份 / Enable Copy From Previous", overwrite: "覆盖保护 / Overwrite Protection",
    applications: "Relativity 应用 / Relativity Applications", disabled: "已禁用 / Disabled",
    defaultCategory: "默认分区 / Default Category", categoryName: "分区名称 / Category Name",
    addCategory: "添加分区 / Add Category", removeCategory: "删除分区 / Delete category",
    removeCategoryHint: "删除此分区及其布局项，字段本身保留。 / Remove this section and its layout items; the fields are retained.",
    moveUp: "上移分区 / Move category up", moveDown: "下移分区 / Move category down",
    options: "布局选项 / Layout Options", properties: "属性 / Properties", sectionProperties: "分区属性 / Section Properties", help: "上下文说明 / Contextual Help",
    helpEditor: "说明编辑器 / HTML Editor", editHelp: "编辑说明 / Edit contextual help",
    bold: "加粗 / Bold", italic: "斜体 / Italic", underline: "下划线 / Underline", bullets: "项目符号 / Bullets",
    helpExample: "填入截图说明 / Use screenshot instructions",
    exampleHelp: "Confirm document coding, redactions (if applicable), and production approval are complete. Identify issues as appropriate and assign to a production.",
    collapsible: "可折叠 / Collapsible", collapsed: "默认折叠 / Collapsed By Default",
    searchFields: "搜索要添加的字段 / Search for a field to add", emptyFields: "没有可添加的匹配字段 / No matching fields available",
    selectCategory: "先添加或选择一个分区，再添加字段。 / Add or select a category before adding a field.",
    dropField: "放置字段 / Drop Field", addField: "添加字段 / Add field", removeField: "移除字段 / Remove field",
    field: "字段 / Field", display: "显示方式 / Display Type", showName: "显示字段名 / Show Field Name",
    customLabel: "自定义标签 / Custom Label", readOnly: "只读 / Read-only", allowCopy: "允许复制上一份 / Allow Copy from Previous",
    copyDisabled: "请先在布局信息中启用复制上一份。 / Enable Copy From Previous in Layout Information first.",
    repeatColumns: "重复列数 / Repeat Columns", defaultRepeatColumns: 1, repeatOptions: [1, 2, 3, 4],
    displayOptions: { text: "文本框 / Text Box", dropdown: "下拉框 / Drop-down", checkbox: "复选框列表 / Check Box List" },
    column: "列 / Column", row: "行 / Row", left: "左列 / Left", right: "右列 / Right",
    saveClose: "保存并关闭 / Save and Close", saved: "布局已保存 / Layout saved", dirty: "尚有未保存的更改 / Unsaved changes",
    closeTitle: "关闭布局编辑器 / Close layout editor", discard: "放弃更改 / Discard changes", keepEditing: "继续编辑 / Keep editing",
    discardHint: "保存更改，或放弃上次保存之后的修改。 / Save changes or discard edits since the last save.",
    deleteTitle: "删除布局 / Delete layout", deleteHint: "删除此布局，字段和选项仍然保留。 / Delete this layout; fields and choices are retained.",
    duplicate: "已存在同名布局。 / A layout with this name already exists.",
    invalidCategory: "请为每个分区填写名称。 / Enter a name for each category.",
    fieldInUse: "此字段正在被布局使用，请先从布局中移除。 / This field is used in a layout. Remove it from the layout first.",
    loadFields: "载入截图示例字段 / Load screenshot fields", loadedFields: "示例字段已就绪，已有同名字段保持原值。 / Example fields ready; existing fields are preserved.",
    exampleFields: [
      { key: "custodian", name: "Custodian", type: "singleObject" },
      { key: "reviewComplete", name: "Review Complete - 2nd Level Review", type: "boolean" },
      { key: "responsiveness", name: "Responsiveness", type: "single" },
      { key: "privilege", name: "Privilege", type: "single" },
      { key: "confidentiality", name: "Confidentiality", type: "single" },
      { key: "issues", name: "Issues", type: "multiple" },
      { key: "privacy", name: "Privacy Redaction Completed", type: "boolean" },
      { key: "approvals", name: "Production Approvals", type: "multiple" },
      { key: "productions", name: "Productions", type: "multipleObject" },
    ],
    financial: "Financial",
    preview: "预览布局 / Preview layout", previewHint: "使用演示文档试填；关闭预览后不保留试填内容。 / Try with sample documents; entries are discarded when this preview closes.",
    previewDocument: "演示文档 / Sample document", previousCopy: "复制上一份 / Copy from previous", copied: "已复制允许复制的可编辑字段 / Eligible editable fields copied",
    previewDocuments: ["DEMO-0001", "DEMO-0002"], sampleCustodian: "林然 / Ran Lin",
    noChoices: "此字段尚未配置选项 / No choices configured for this field",
    noSections: "此布局尚未添加分区 / No categories in this layout", previewEmpty: "未填写 / Not entered",
    orderReferenceHint: "数值越小越靠前。 / Layouts with lower order values appear first.",
    columns: ["对象类型 / Object Type", "名称 / Name", "顺序 / Order", "启用复制上一份 / Enable Copy From Previous"],
    separator: " · ", numberingStart: 1, defaultOrder: 0,
  },
  workspaceManagement: {
    title: "客户、事项与工作区 / Clients, Matters & Workspaces",
    subtitle: "先确定客户和事项，再创建承载数据、权限与审阅流程的工作区 / Establish the client and matter before creating the workspace that contains data, permissions, and review workflows",
    ids: "Case Administration",
    tabs: [
      { id: "clients", label: "客户 / Clients" },
      { id: "matters", label: "事项 / Matters" },
      { id: "workspaces", label: "工作区 / Workspaces" },
    ],
    hierarchyTitle: "对象关系 / Object hierarchy",
    hierarchyClient: "客户 / Client",
    hierarchyMatter: "事项 / Matter",
    hierarchyWorkspace: "工作区 / Workspace",
    hierarchyDescription: "Client 管理委托方归属；Matter 记录具体案件或调查；Workspace 是导入、处理、搜索、审阅和交付实际发生的环境。 / Client identifies the organization, Matter records the case or investigation, and Workspace is where ingestion, processing, search, review, and production occur.",
    allClients: "全部客户 / All Clients",
    allMatters: "全部事项 / All Matters",
    allWorkspaces: "全部工作区 / All Workspaces",
    newClient: "新建客户 / New Client",
    newMatter: "新建事项 / New Matter",
    newWorkspace: "新建工作区 / New Workspace",
    listFeedback: "列表反馈 / List feedback",
    pinTitle: "固定常用工作区 / Pin Favorite Workspaces",
    pinDescription: "固定后，该工作区会显示在列表顶部。 / Pinned workspaces appear at the top of the list.",
    details: "记录详情 / Record details",
    selectRecord: "选择一条记录查看详情 / Select a record to view details",
    clientInformation: "客户信息 / Client Information",
    otherClientDetails: "其他客户信息 / Other Client Details",
    matterInformation: "事项信息 / Matter Information",
    workspaceInformation: "工作区信息 / Workspace Information",
    advancedSettings: "高级设置 / Advanced Settings",
    other: "其他 / Other",
    recordHistory: "记录历史 / Record History",
    name: "名称 / Name",
    number: "编号 / Number",
    clientNumber: "客户编号 / Client Number",
    matterNumber: "事项编号 / Matter Number",
    status: "状态 / Status",
    client: "客户 / Client",
    matter: "事项 / Matter",
    workspace: "工作区 / Workspace",
    templateWorkspace: "模板工作区 / Template Workspace",
    keywords: "关键词 / Keywords",
    notes: "备注 / Notes",
    clientDomainStatus: "客户域状态 / Client Domain Status",
    nonClientDomain: "非客户域 / Non-Client Domain",
    caseArtifactId: "Case Artifact ID",
    createdBy: "创建人 / Created by",
    createdOn: "创建时间 / Created on",
    lastModifiedBy: "最后修改人 / Last modified by",
    lastModifiedOn: "最后修改时间 / Last modified on",
    active: "活动 / Active",
    inactive: "停用 / Inactive",
    saveAndNew: "保存并新建 / Save & New",
    saveAndBack: "保存并返回 / Save & Back",
    editPermissions: "编辑权限 / Edit Permissions",
    viewAudit: "查看审计 / View Audit",
    delete: "删除 / Delete",
    pin: "固定工作区 / Pin workspace",
    unpin: "取消固定 / Unpin workspace",
    openWorkspace: "打开工作区 / Open workspace",
    select: "请选择 / Select",
    notProvided: "未填写 / Not provided",
    requiredHint: "请完成所有必填字段。 / Complete all required fields.",
    clientCreated: "客户已创建 / Client created",
    matterCreated: "事项已创建并关联客户 / Matter created and linked to client",
    workspaceCreated: "工作区已创建并继承事项与客户归属 / Workspace created with matter and client context",
    auditDemo: "审计记录已在详情中展示 / Audit history is shown in the details panel",
    permissionsDemo: "权限配置入口已打开（演示） / Permission editor opened (demo)",
    clientPlaceholder: "例如：ARK Industries / e.g. ARK Industries",
    clientNumberPlaceholder: "例如：12345 / e.g. 12345",
    matterPlaceholder: "例如：ARK Industries vs. Dknight Enterprises",
    matterNumberPlaceholder: "例如：MAT-2026-001",
    workspacePlaceholder: "例如：ARK Dknight Review",
    keywordsPlaceholder: "可选关键词 / Optional keywords",
    notesPlaceholder: "记录事项背景或管理备注 / Record matter context or administrative notes",
    columns: {
      clients: ["名称 / Name", "编号 / Number", "状态 / Status", "客户域 / Client Domain", "事项 / Matters"],
      matters: ["名称 / Name", "编号 / Number", "客户名称 / Client Name", "客户编号 / Client Number", "状态 / Status"],
      workspaces: ["固定 / Pin", "名称 / Name", "Case Artifact ID", "客户名称 / Client Name", "事项名称 / Matter Name", "状态 / Status"],
    },
    clients: [
      { id: "client-ark", name: "ARK Industries", number: "12345", status: "活动 / Active", domain: "非客户域 / Non-Client Domain" },
      { id: "client-close", name: "Close AI Ltd.", number: "CL-2026-008", status: "活动 / Active", domain: "客户域 / Client Domain" },
    ],
    matters: [
      { id: "matter-ark", name: "ARK Industries vs. Dknight Enterprises", number: "MAT-2026-001", clientId: "client-ark", clientName: "ARK Industries", clientNumber: "12345", status: "活动 / Active", keywords: "", notes: "" },
      { id: "matter-mark", name: "高管马克欺诈项目调查 / Project Mark Fraud", number: "MAT-2026-008", clientId: "client-close", clientName: "Close AI Ltd.", clientNumber: "CL-2026-008", status: "活动 / Active", keywords: "fraud", notes: "" },
    ],
    workspaces: [
      { id: "workspace-ark", name: "ARK Industries vs. Dknight Enterprises", matterId: "matter-ark", matterName: "ARK Industries vs. Dknight Enterprises", clientName: "ARK Industries", artifactId: "1387894", template: "RelativityOne Review Template (v4.0.0)", status: "活动 / Active", pinned: false },
      { id: "workspace-mark", name: "马克欺诈项目工作区 / MF Workspace", matterId: "matter-mark", matterName: "高管马克欺诈项目调查 / Project Mark Fraud", clientName: "Close AI Ltd.", artifactId: "1387942", template: "RelativityOne Investigations Template (v2.1.1)", status: "活动 / Active", pinned: true },
    ],
    templates: [
      "RelativityOne Review Template (v4.0.0)",
      "RelativityOne Review Template (v3.0.0)",
      "RelativityOne Investigations Template (v2.1.1)",
      "RelativityOne Hold and Collect Template (v2.0.2)",
      "RelativityOne ECA Template",
    ],
    history: {
      actor: "Moore, Scotti-Lynn",
      created: "2024-03-26 17:12 MDT",
      modified: "2024-03-26 17:12 MDT",
    },
  },
  permissionManagement: {
    title: "工作区安全 / Workspace Security", groups: "组 / Groups",
    features: "功能 / Features", objects: "对象安全 / Object Security", tabs: "标签可见性 / Tab Visibility", other: "其他设置 / Other Settings",
    selectedGroup: "所选组 / Selected Group", edit: "编辑权限 / Edit Permissions", copy: "复制 / Copy", preview: "预览 / Preview",
    loadExamples: "载入截图示例组 / Load example groups", examplesLoaded: "示例组已载入，可开始配置权限。 / Example groups loaded.",
    exampleHint: "可关联已有组，或载入教程中的示例组开始体验。 / Assign an existing group or load tutorial example groups.",
    search: "搜索权限 / Search permissions", details: "查看详情 / See Details", collapse: "收起详情 / Collapse details",
    role: "角色 / Role", reviewer: "审阅员 / Reviewer", powerUser: "高级用户 / Power User", administrator: "管理员 / Administrator",
    roleBoundary: "截图未展开 Administrator 的具体权限，本原型暂不提供该角色配置。 / Administrator permissions are not expanded in the screenshots and are unavailable in this prototype.",
    reviewActions: "审阅 — 操作 / Review — Actions", reviewApps: "审阅 — 应用 / Review — Applications",
    reviewCenter: "审阅中心 / Review Center", manageImage: "管理文档图像 / Manage Document Image", code: "修改文档元数据（编码）/ User Modify Document Metadata (Code)", sentiment: "查看情绪分析 / User View Sentiment Analysis",
    objectItems: "对象权限项 / Object Security Items", tabItems: "可见标签 / Tab Visibility Items",
    permissionName: "权限名称 / Permission Name", none: "无 / None", view: "查看 / View", editAction: "编辑 / Edit", deleteAction: "删除 / Delete", add: "添加 / Add", editSecurity: "编辑安全性 / Edit Sec",
    on: "开启 / On", off: "关闭 / Off", actions: "操作 / Actions",
    objectRows: [
      { id: "batch", label: "批次 / Batch" }, { id: "field", label: "字段 / Field" }, { id: "folder", label: "文件夹 / Folder" },
      { id: "dashboard", label: "仪表盘 / Dashboard" }, { id: "layout", label: "布局 / Layout" }, { id: "document", label: "文档 / Document" },
      { id: "redaction", label: "遮盖 / Redaction" }, { id: "massOperation", label: "批量操作 / Mass Operation" }, { id: "list", label: "列表 / List" },
      { id: "search", label: "搜索 / Search" }, { id: "searchIndex", label: "搜索索引 / Search Index" }, { id: "tab", label: "标签 / Tab" },
      { id: "searchFolder", label: "搜索文件夹 / Search Folder" }, { id: "view", label: "视图 / View" }, { id: "workspace", label: "工作区 / Workspace" },
    ],
    documentActions: [
      { id: "uploadImage", label: "上传图像 / Upload Image" }, { id: "replaceDocument", label: "替换文档 / Replace Document" },
      { id: "createPdf", label: "创建 PDF / Create PDF" }, { id: "localAccess", label: "本地访问（下载、复制文本） / Local Access (Download, Copy Text)" },
      { id: "redactDocument", label: "遮盖文档 / Redact Document" }, { id: "highlightDocument", label: "高亮文档 / Highlight Document" },
      { id: "addImage", label: "添加图像 / Add Image" }, { id: "deleteImage", label: "删除图像 / Delete Image" }, { id: "newDocument", label: "新建文档 / New Document" },
    ],
    tabRows: [
      { id: "reviewQueues", label: "审阅队列 / Review Queues" }, { id: "documents", label: "文档 / Documents" },
      { id: "reviewCenter", label: "审阅中心 / Review Center" }, { id: "lists", label: "列表 / Lists" },
      { id: "reviewManagement", label: "审阅管理 / Review Management" },
    ],
    settingSections: [
      { id: "browsers", label: "浏览器 / Browsers", items: [
        { id: "folders", label: "文件夹 / Folders" }, { id: "fieldTree", label: "字段树 / Field Tree" },
        { id: "savedSearches", label: "高级与已保存搜索 / Advanced & Saved Searches" }, { id: "documentPreview", label: "文档预览 / Document Preview" },
      ] },
      { id: "mass", label: "批量操作 / Mass Operations", items: [{ id: "exportFile", label: "导出至文件 / Export to File" }, { id: "saveList", label: "保存为列表 / Save as List" }] },
      { id: "admin", label: "管理操作 / Admin Operations", items: [{ id: "pivot", label: "使用透视表与图表 / Use Pivot/Chart" }, { id: "quickNav", label: "使用快速导航 / Use Quick Nav" }, { id: "exportDashboard", label: "导出仪表盘 / Export Dashboard" }] },
    ],
    reviewSave: "复核并保存 / Review and Save", revert: "撤回全部更改 / Revert All", summary: "复核权限变更 / Review Permissions Changes",
    summaryHint: "以下为本次修改的功能及细粒度权限，保存后对所选组生效。 / Review this session’s feature and granular changes before saving.",
    featureChanges: "功能变更 / Features changes", granularChanges: "细粒度权限变更 / Granular permissions changes",
    before: "修改前 / Before", after: "修改后 / After", noChanges: "没有待保存的变更。 / No pending changes.",
    saved: "组权限已保存。 / Group permissions saved.", discardTitle: "放弃未保存的权限更改？ / Discard unsaved permission changes?",
    discardMessage: "离开后将恢复上次保存的权限。 / Leaving restores the last saved permissions.", discard: "放弃更改 / Discard changes", keepEditing: "继续编辑 / Keep editing",
    copyTitle: "复制组权限 / Copy Group Permissions", copyFrom: "复制自 / Copy From", copyTo: "复制到 / Copy To", copyPermissions: "复制权限 / Copy Permissions",
    copyHint: "将用来源组的已保存权限替换目标组在当前工作区的权限。组成员不受影响。 / Replace the target’s permissions in this workspace with the source’s saved permissions. Membership is unchanged.",
    copied: "权限已复制。 / Permissions copied.", noSource: "请先关联另一个组作为权限来源。 / Assign another group to use as the source.",
    previewAs: "正在以此组成员身份预览 / Previewing as a member of", exitPreview: "退出预览 / Exit Preview", previewPages: "页面预览 / Page Preview", previewSettings: "权限设置 / Permission Settings",
    previewSettingsHint: "以下内容是该组在此工作区的只读权限快照。 / Read-only permission snapshot for this group in this workspace.",
    previewGroup: "预览组 / Preview Group", previewWorkspace: "预览工作区 / Preview Workspace", openPreview: "打开预览 / Open Preview", previewUnavailable: "没有可预览的组或工作区。 / No group or workspace is available to preview.",
    noTabs: "此组没有可预览的标签。 / No visible tabs for this group.", noObjectAccess: "此组无权查看此对象。 / This group cannot view this object.",
    noQueues: "没有可用队列 / No Queues Available", noAssignedQueues: "尚未分配任何队列。 / You have not been added to any queues.", noWorkspaceQueues: "工作区内没有审阅队列。 / No review queues in workspace.",
    library: "审阅库 / Review Library", queueTemplates: "队列模板 / Queue Templates", queueType: "队列类型 / Queue Type", savedSearch: "已保存搜索 / Saved Search", prioritized: "优先审阅 / Prioritized Review",
    libraryRows: ["1. 1st Level Review-Threaded", "2. 2nd Level Review-Privilege Term QC", "3. 2nd Level Review-Significant QC", "4. Prioritized Review", "5. Docs with Ranks Below Zero", "6. Images", "7. Spreadsheets", "8. Model/Reviewer QC", "9. New Blank Queue"], prioritizedRow: 3,
    documentColumns: ["控制编号 / Control Number", "文档族 / Family Group", "保管人 / Custodian", "记录类型 / Record Type"],
    workspaceInfo: "工作区信息 / Workspace Information", advanced: "高级设置 / Advanced Settings", resourceInfo: "资源信息 / Resource Information", resourcePool: "资源池 / Resource Pool", databaseLocation: "数据库位置 / Database Location", defaultFileRepository: "默认文件仓储 / Default File Repository", dataGridFileRepository: "Data Grid 文件仓储 / Data Grid File Repository", defaultCacheLocation: "默认缓存位置 / Default Cache Location", downloadHandlerUrl: "下载处理程序 URL / Download Handler URL", sqlFullTextLanguage: "SQL 全文语言 / SQL Full Text Language", workspaceAdminGroup: "工作区管理员组 / Workspace Admin Group", selectAdmin: "选择项目 — 工作区管理员组 / Select Item — Workspace Admin Group", set: "设置 / Set", advancedSaved: "工作区高级设置已保存。 / Workspace advanced settings saved.",
    statusActive: "活动 / Active", statusPendingDecommission: "待停用 / Pending Decommission", statusInactive: "停用 / Inactive", statusOptions: ["活动 / Active", "待停用 / Pending Decommission", "停用 / Inactive"],
    resourceOptions: ["默认资源池 / Default Resource Pool", "主资源池 / Primary Resource Pool"], databaseOptions: ["主数据库 / Primary Database", "辅助数据库 / Secondary Database"], repositoryOptions: ["默认文件仓储 / Default File Repository", "主文件仓储 / Primary File Repository"], cacheOptions: ["默认缓存位置 / Default Cache Location", "高速缓存位置 / High-speed Cache Location"], sqlLanguages: ["Arabic", "Bangla", "Bengali (India)", "Bokmål", "Brazilian", "British English", "Bulgarian", "Catalan", "Chinese (Hong Kong SAR, PRC)", "Chinese (Macao SAR)", "Chinese (Singapore)", "Croatian", "Czech", "Danish", "Dutch", "English", "Estonian", "Finnish", "French", "German", "Greek", "Gujarati", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Italian", "Japanese", "Kannada", "Korean", "Latvian", "Lithuanian", "Malay - Malaysia", "Malayalam", "Marathi", "Neutral", "Norwegian", "Polish", "Portuguese (Brazil)", "Portuguese (Portugal)", "Punjabi", "Romanian", "Russian", "Serbian (Cyrillic)", "Serbian (Latin)", "Simplified Chinese", "Slovak", "Slovenian", "Spanish", "Swedish", "Tamil", "Telugu", "Thai", "Traditional Chinese", "Turkish", "Ukrainian", "Urdu", "Vietnamese"], downloadHandlerDefault: "Relativity.Distributed",
    keywordsHint: "可选关键词 / Optional keywords", notesHint: "记录工作区用途或管理备注 / Record workspace purpose or administrative notes",
    seedGroupIdStart: 1389000,
    seedGroups: [
      { id: "example-administrator", name: "AF Administrator", assigned: true },
      { id: "example-attorneys", name: "AF Staff Attorneys", assigned: true },
      { id: "example-automated", name: "Automated Workflow Application", assigned: true },
      { id: "example-kcura", name: "kCura Admin Group", assigned: true },
      { id: "example-native", name: "NativeRedactServiceGroup", assigned: true },
      { id: "example-template-admin", name: "Review Template - Administrator", assigned: true },
      { id: "example-template-attorney", name: "Review Template - Attorney", assigned: true },
      { id: "example-template-level1", name: "Review Template - Level 1 Reviewer", assigned: true },
      { id: "example-template-level2", name: "Review Template - Level 2 Reviewer", assigned: true },
      { id: "example-template-manager", name: "Review Template - Review Manager", assigned: true },
      { id: "example-manager", name: "AF Review Manager", assigned: false },
      { id: "example-qc", name: "AF QC Reviewers", assigned: false },
    ],
    exampleDate: "2026-09-23", separator: " · ", valueSeparator: ", ",
  },
  userManagement: {
    title: "用户与组管理 / User and Group Management",
    subtitle: "创建用户，将用户加入组，再将组关联到工作区。用户通过所属组获得工作区访问权限。 / Create users, add users to groups, then associate groups with workspaces to grant access.",
    ids: "User and Group Management",
    users: "用户 / Users", groups: "组 / Groups",
    allUsers: "全部用户 / All Users", allGroups: "全部组 / All Groups",
    newUser: "新建用户 / New User", newGroup: "新建组 / New Group",
    userInformation: "用户信息 / User Information", otherUserDetails: "其他用户信息 / Other User Details",
    groupInformation: "组信息 / Group Information", otherGroupDetails: "其他组信息 / Other Group Details",
    workspaceAssociations: "关联工作区 / Workspace Associations", saveWorkspaceAssociations: "保存工作区关联 / Save Workspace Associations", workspaceAssociationsSaved: "工作区关联已保存。 / Workspace associations saved.",
    firstName: "名 / First Name", lastName: "姓 / Last Name", email: "电子邮箱 / Email",
    fullName: "姓名 / Full Name", type: "类型 / Type", userType: "用户类型 / User Type",
    internal: "内部 / Internal", groupType: "组类型 / Group Type", systemGroup: "系统组 / System Group",
    access: "访问 / Access", relativityAccess: "Relativity 访问 / Relativity Access",
    disableOn: "停用日期（UTC）/ Disable On Date (UTC)", trustedIPs: "可信 IP / Trusted IPs",
    trustedIPsHint: "每行填写一个 IP 地址。 / Place each IP address on a separate line.",
    permissions: "权限 / Permissions", changeSettings: "更改设置 / Change Settings",
    changeViewer: "更改文档查看器 / Change Document Viewer", documentSkip: "文档跳过 / Document Skip",
    shortcuts: "键盘快捷键 / Keyboard Shortcuts", defaults: "默认设置 / Defaults",
    pageLength: "列表每页条数 / Item List Page Length", pageLengths: ["10", "25", "50", "100"],
    viewerPreference: "文档查看偏好 / Document Viewer Preference", viewer: "查看器 / Viewer",
    documentViewer: "文档查看器 / Document Viewer", defaultViewer: "默认 / Default",
    searchOwner: "已保存搜索所有者 / Saved Search Owner", public: "公开 / Public", user: "用户 / User",
    notifications: "用户组邮件通知 / User Group Email Notifications",
    notificationOptions: ["接收全部 / Receive All", "仅接收错误 / Receive Errors Only", "不接收 / Do Not Receive"],
    showFilters: "显示筛选器 / Show Filters", skipPreference: "文档跳过偏好 / Document Skip Preference", normal: "普通 / Normal",
    initialSettings: { pageLength: "25", viewerPreference: "查看器 / Viewer", searchOwner: "用户 / User", notifications: "接收全部 / Receive All" },
    testUsers: [
      { id: "user-ran", firstName: "然 / Ran", lastName: "林 / Lin", email: "ran.lin@example.com", type: "内部 / Internal", clientId: "client-close", access: true, disableOn: "", trustedIPs: "", changeSettings: true, changeViewer: true, documentSkip: true, shortcuts: true, pageLength: "25", viewerPreference: "查看器 / Viewer", searchOwner: "用户 / User", notifications: "接收全部 / Receive All", showFilters: true, keywords: "workspace administration", notes: "负责两个演示工作区的配置。", createdOn: "2026-09-25 09:00:00", modifiedOn: "2026-09-30 09:45:00" },
      { id: "user-yue", firstName: "悦 / Yue", lastName: "陈 / Chen", email: "yue.chen@example.com", type: "内部 / Internal", clientId: "client-close", access: true, disableOn: "", trustedIPs: "", changeSettings: false, changeViewer: false, documentSkip: true, shortcuts: true, pageLength: "25", viewerPreference: "查看器 / Viewer", searchOwner: "用户 / User", notifications: "接收全部 / Receive All", showFilters: true, keywords: "first pass review", notes: "MF Workspace 一审律师。", createdOn: "2026-09-25 09:10:00", modifiedOn: "2026-09-30 09:40:00" },
      { id: "user-ning", firstName: "宁 / Ning", lastName: "周 / Zhou", email: "ning.zhou@example.com", type: "内部 / Internal", clientId: "client-close", access: true, disableOn: "", trustedIPs: "", changeSettings: false, changeViewer: true, documentSkip: true, shortcuts: true, pageLength: "50", viewerPreference: "查看器 / Viewer", searchOwner: "公开 / Public", notifications: "仅接收错误 / Receive Errors Only", showFilters: true, keywords: "quality control", notes: "MF Workspace 质检复核。", createdOn: "2026-09-25 09:20:00", modifiedOn: "2026-09-30 09:42:00" },
      { id: "user-lan", firstName: "岚 / Lan", lastName: "王 / Wang", email: "lan.wang@example.com", type: "内部 / Internal", clientId: "client-ark", access: true, disableOn: "", trustedIPs: "", changeSettings: false, changeViewer: false, documentSkip: true, shortcuts: true, pageLength: "25", viewerPreference: "查看器 / Viewer", searchOwner: "用户 / User", notifications: "接收全部 / Receive All", showFilters: true, keywords: "ARK review", notes: "ARK Workspace 审阅人员。", createdOn: "2026-09-25 09:30:00", modifiedOn: "2026-09-30 09:38:00" },
      { id: "user-scotti", firstName: "Lynn", lastName: "Scotti-Lynn, Moore", email: "scotti.moore@example.com", type: "内部 / Internal", clientId: "client-ark", access: true, disableOn: "", trustedIPs: "", changeSettings: true, changeViewer: false, documentSkip: true, shortcuts: true, pageLength: "25", viewerPreference: "查看器 / Viewer", searchOwner: "用户 / User", notifications: "接收全部 / Receive All", showFilters: true, keywords: "review manager", notes: "ARK Workspace 管理与复核。", createdOn: "2026-09-25 09:40:00", modifiedOn: "2026-09-30 09:35:00" },
    ],
    testGroups: [
      { id: "group-mf-reviewers", name: "MF Workspace Reviewers", clientId: "client-close", userIds: ["user-yue", "user-ning"], workspaceIds: ["workspace-mark"], keywords: "first pass", notes: "MF Workspace 一审与质检。", createdOn: "2026-09-25 10:00:00", modifiedOn: "2026-09-30 09:45:00" },
      { id: "group-mf-managers", name: "MF Workspace Managers", clientId: "client-close", userIds: ["user-ran"], workspaceIds: ["workspace-mark"], keywords: "administration", notes: "MF Workspace 管理组。", createdOn: "2026-09-25 10:05:00", modifiedOn: "2026-09-30 09:45:00" },
      { id: "group-ark-reviewers", name: "ARK Workspace Reviewers", clientId: "client-ark", userIds: ["user-lan"], workspaceIds: ["workspace-ark"], keywords: "review", notes: "ARK Workspace 审阅组。", createdOn: "2026-09-25 10:10:00", modifiedOn: "2026-09-30 09:38:00" },
      { id: "group-ark-managers", name: "ARK Workspace Managers", clientId: "client-ark", userIds: ["user-ran", "user-scotti"], workspaceIds: ["workspace-ark"], keywords: "administration", notes: "ARK Workspace 管理组。", createdOn: "2026-09-25 10:15:00", modifiedOn: "2026-09-30 09:38:00" },
    ],
    enableUser: "启用用户 / Enable User",
    enableMessage: "启用 Relativity Access 后，此用户可访问 Relativity，并计入席位总数。是否继续？ / Setting Relativity Access to Yes allows access and counts this user toward the total seat count. Continue?",
    yes: "是 / Yes", no: "否 / No", enabled: "已启用 / Enabled", disabled: "已停用 / Disabled",
    requiredHint: "请填写所有必填字段，并选择客户。 / Complete all required fields and select a client.",
    invalidEmail: "请输入有效的电子邮箱。 / Enter a valid email address.",
    duplicateEmail: "该电子邮箱已存在。 / This email address already exists.",
    duplicateGroup: "该客户下已存在同名组。 / A group with this name already exists for the client.",
    invalidIPs: "请每行填写一个有效的 IPv4 或 IPv6 地址。 / Enter one valid IPv4 or IPv6 address per line.",
    invalidDate: "请选择有效的 UTC 停用日期和时间。 / Choose a valid UTC disable date and time.",
    userSaved: "用户已保存。 / User saved.", groupSaved: "组已保存。 / Group saved.",
    deleted: "记录已删除。 / Record deleted.", deleteTitle: "删除记录 / Delete record",
    deleteMessage: "删除用户会移除其组成员关系；删除组会移除其工作区关联。是否继续？ / Deleting a user removes group membership; deleting a group removes workspace associations. Continue?",
    noData: "暂无数据 / No data.", noUsers: "尚未创建用户，点击“新建用户”开始。 / Click New User to add your first user.",
    noGroups: "尚未创建组，点击“新建组”开始。 / Click New Group to create your first group.",
    searchUsers: "搜索姓名、邮箱或客户 / Search name, email or client", searchGroups: "搜索组名称或客户 / Search group name or client",
    total: "总计 / Total:", selected: "已选择 / Selected:", selectAll: "选择全部 / Select all",
    add: "添加 / Add", remove: "移除 / Remove", apply: "应用 / Apply", okay: "确定 / Okay",
    editGroupMembership: "编辑组归属 / Edit Group Membership", selectGroups: "选择组 / Select Groups", selectedGroups: "已加入的组 / Selected Groups", groupMembershipSaved: "用户的组归属已保存。 / User group membership saved.",
    selectClient: "选择客户 / Select Client", clientSearch: "搜索客户 / Search clients",
    selectUsers: "选择项目 — 用户 / Select Items — Users", availableUsers: "可选用户 / Available Users", selectedUsers: "待加入的用户 / Selected Users",
    moveRight: "移至右侧 / Move to right", moveLeft: "移至左侧 / Move to left",
    moveAllRight: "全部移至右侧 / Move all to right", moveAllLeft: "全部移至左侧 / Move all to left",
    filter: "筛选 / Filter", addedTitle: "用户已加入组 / User(s) added to Group",
    addedMessage: "本地演示已完成成员更新。真实系统会提交后台任务，并根据通知设置发送完成邮件。 / Membership updated in this local demo. The live system submits a job and sends email according to notification settings.",
    removed: "已移除所选成员。 / Selected members removed.",
    manageWorkspacePermissions: "管理工作区权限 / Manage Workspace Permissions",
    selectedWorkspace: "所选工作区 / Selected Workspace", groupList: "组列表 / Group List",
    addRemoveGroups: "添加 / 移除组 / Add / Remove Groups", availableGroups: "可选组 / Available Groups",
    groupsInWorkspace: "工作区内的组 / Groups in Workspace", viewUsers: "查看用户 / View Users",
    permissionsSaved: "工作区的组关联已保存。 / Workspace group associations saved.",
    previewSecurity: "预览权限设置 / 页面 / Preview Permissions & Pages",
    securityBoundary: "用户通过所属组获得工作区权限，可编辑权限或预览组成员能看到的页面。 / Edit workspace group permissions or preview the pages available to group members.",
    localOnly: "本地交互演示；刷新页面后恢复初始数据，不会创建真实账号、计费或发送邮件。 / Local demo; reloading resets data. No live accounts, billing or emails.",
    accessHint: "工作区访问还取决于用户启用状态及停用日期。 / Workspace access also depends on the user's enabled status and disable date.",
    columns: {
      users: ["姓名 / Full Name", "客户 / Client", "电子邮箱 / E-mail Address", "客户名称 / Client Name", "用户类型 / User Type", "创建人 / Created By", "创建时间 / Created On"],
      groups: ["Artifact ID", "组名称 / Group Name", "客户 / Client"],
      members: ["姓名 / Full Name", "电子邮箱 / E-mail Address", "用户类型 / User Type"],
      workspaces: ["名称 / Name", "客户名称 / Client Name", "事项名称 / Matter Name", "状态 / Status"],
    },
    idStart: 1387968,
    nameSeparator: ", ",
    dateLocale: "zh-CN",
  },
  scope: {
    title: "P0 + P1 范围追溯 / P0 + P1 Scope Traceability",
    intro: "原型按 Relativity 原始功能结构呈现关键任务流。每个页面显示对应功能 ID；中文为对照翻译，不改变原始英文能力边界。 / The prototype follows the original Relativity capability structure. Each page shows source feature IDs; Chinese is a parallel translation and does not redefine the English capability boundary.",
    total: "127 项 / items",
    totalNumber: "127",
    p0: "57 项 P0 / P0 items",
    p1: "70 项 P1 / P1 items",
    groups: [
      { title: "数据输入与处理 / Data ingestion & processing", ids: "REL-063–083", count: "21 P0" },
      { title: "分析 / Analytics", ids: "REL-084–103", count: "20 P1" },
      { title: "文档、搜索与审阅 / Documents, search & review", ids: "REL-116–148", count: "33 P0" },
      { title: "成像、OCR 与 PDF / Imaging, OCR & PDF", ids: "REL-149–163", count: "15 P1" },
      { title: "遮盖 / Redact", ids: "REL-164–178", count: "15 P1" },
      { title: "制作 / Production", ids: "REL-179–192", count: "14 P1" },
      { title: "平台与审阅状态 / Platform & review status", ids: "REL-372–373, 379–380, 384, 390", count: "6 P1" },
      { title: "关系、传播与导入导出 / Relations, propagation & import/export", ids: "REL-386–387, 394", count: "3 P0" },
    ],
    boundaryTitle: "原型边界 / Prototype boundary",
    boundary: "已覆盖关键成功路径及处理异常、索引等待、审阅占用、遮盖泄漏检查和制作校验失败。未连接真实后端，也未验证真实租户中的按钮位置与权限组合。 / Covers the critical happy path plus processing exceptions, index waiting, review locks, redaction leak checks, and production validation failures. No live backend is connected, and exact controls or permission combinations have not been tenant-verified.",
  },
  home: {
    title: "工作区概览 / Workspace Overview",
    subtitle: "从数据进入到正式交付的当前状态 / Current state from ingestion through delivery",
    ids: "跨页面 / Cross-page",
    welcome: "下午好，林然 / Good afternoon, Ran",
    nextAction: "建议下一步 / Recommended next action",
    nextActionText: "复核 3 处待确认遮盖，然后运行制作前校验。 / Review 3 pending redactions, then run pre-production validation.",
    continueReview: "继续复核 / Continue QC",
    dataEntryTitle: "数据进入工作区 / Bring data into workspace",
    dataEntrySubtitle: "从 Import/Export 选择数据类型；非结构化原始文件将进入 Processing。 / Choose a data type in Import/Export; unstructured raw files continue to Processing.",
    structuredImport: "导入结构化数据 / Import structured data",
    structuredImportDetail: "Load file、图片、文本或 RDO 数据。 / Load files, images, text, or RDO data.",
    rawImport: "添加非结构化数据 / Add unstructured data",
    rawImportDetail: "导入原始文件并交给 Processing 处理。 / Import raw files and send them to Processing.",
    structuredImportPending: "结构化导入页面将在后续版本补充。 / The structured import page will be added in a later version.",
    stagesTitle: "证据处理链 / Evidence workflow",
    stages: [
      { label: "导入与处理 / Ingest & Process", value: "12,480", detail: "11,946 已发布 / published", tone: "success", target: "processing" },
      { label: "搜索与分析 / Search & Analyze", value: "10,932", detail: "索引覆盖 / indexed", tone: "info", target: "analytics" },
      { label: "审阅 / Review", value: "4,280", detail: "2,914 已编码 / coded", tone: "warning", target: "review" },
      { label: "遮盖与质检 / Redact & QC", value: "86", detail: "3 待复核 / pending", tone: "danger", target: "redaction" },
      { label: "制作与导出 / Produce & Export", value: "1", detail: "草稿制作集 / draft set", tone: "neutral", target: "production" },
    ],
    metrics: [
      { label: "已发布文档 / Published documents", value: "11,946", delta: "+528 今日 / today" },
      { label: "待处理异常 / Open exceptions", value: "17", delta: "5 可重试 / retryable" },
      { label: "审阅完成率 / Review completion", value: "68.1%", delta: "+6.4% 本周 / this week" },
      { label: "制作阻断项 / Production blockers", value: "3", delta: "均来自遮盖质检 / all from redaction QC" },
    ],
    activityTitle: "最近活动 / Recent activity",
    activities: [
      { time: "14:42", actor: "周宁 / Ning Zhou", action: "提交了遮盖复核 / submitted redaction QC", object: "REL00010342" },
      { time: "14:18", actor: "系统 / System", action: "完成增量索引 / completed incremental index", object: "dtSearch - Morninglight" },
      { time: "13:56", actor: "林然 / Ran Lin", action: "保存了搜索 / saved search", object: "First Pass - Contract Terms" },
      { time: "12:30", actor: "王辰 / Chen Wang", action: "重试处理异常 / retried processing exceptions", object: "PROC-2026-0918-04" },
    ],
    attentionTitle: "需要关注 / Needs attention",
    attention: [
      { title: "加密附件等待密码 / Encrypted attachments need passwords", detail: "8 个文件 / files", target: "processing" },
      { title: "一份文档被其他审阅人占用 / One document is checked out", detail: "REL00010331", target: "review" },
      { title: "遮盖文本层检查未通过 / Redacted text-layer check failed", detail: "3 处标记 / markups", target: "redaction" },
    ],
  },
  rawImportPage: {
    title: "导入非结构化原始数据 / Import unstructured raw data",
    subtitle: "Import/Export → Unstructured Data → Processing / 将未处理的原始文件交给 Processing。",
    ids: "REL-063–071, REL-394",
    back: "返回工作区概览 / Back to workspace overview",
    sourcePanel: "1. 选择原始数据 / 1. Select raw data",
    sourcePanelHint: "选择需要进入 Processing 的原始文件或文件夹。 / Choose raw files or folders that require Processing.",
    chooseFiles: "上传 / Upload",
    selectedFiles: "尚未选择文件 / No files selected",
    demoFiles: ["mailbox-export.pst", "attachments.zip"],
    sourceType: "来源类型 / Source type",
    sourceTypeValue: "原始文件 / Raw files",
    supported: "示例：PST、MSG、EML、PDF、DOCX、XLSX、ZIP。 / Examples: PST, MSG, EML, DOCX, XLSX, and ZIP.",
    processingPanel: "2. 确认导入任务 / 2. Confirm import task",
    processingPanelHint: "导入提交后，系统会自动建立后台批次并进入 Inventory、Discover 和 Publish。 / After submission, the system creates the processing batch and continues to Inventory, Discover, and Publish.",
    importJobName: "导入任务名称 / Import job name",
    importJobNameValue: "共享盘导入 · 2026-09-30 / Shared drive import · 2026-09-30",
    processingProfile: "处理配置 / Processing Profile",
    processingProfileValue: "中国项目默认配置 / China matter default",
    custodian: "保管人 / Custodian",
    custodianValue: "待选择 / Select custodian",
    custodianOptions: ["待选择 / Select custodian", "王辰 / Chen Wang"],
    custodianPanel: "3. 保管人识别与批量预览 / 3. Custodian identification and batch preview",
    custodianPanelHint: "一次提交可以创建多个 Processing Data Sources；系统会先预览识别结果。 / One submission can create multiple Processing Data Sources; review the detected results first.",
    detectionMode: "识别方式 / Identification method",
    autoDetect: "从文件夹结构自动识别 / Detect from folder structure",
    existingEntities: "从已有 Entity 匹配 / Match existing Entities",
    defaultCustodian: "所有文件使用同一个默认 Custodian / Use one default Custodian for all files",
    entityType: "Entity 类型 / Entity type",
    entityPerson: "Person",
    namingConvention: "文件夹格式 / Folder naming convention",
    namingConventionValue: "Last Name, First Name",
    delimiter: "分隔符 / Delimiter",
    delimiterValue: ",",
    analyzeSources: "分析文件夹并预览 / Analyze folders and preview",
    previewSummary: "批量识别结果 / Batch identification result",
    identifiedCustodians: "已识别 custodian / Custodians identified",
    dataSourcesToCreate: "将创建数据源 / Data Sources to create",
    totalFiles: "预计文件数 / Estimated files",
    totalFilesValue: "23,802",
    previewColumns: ["选择 / Select", "Custodian", "数据源路径 / Data source path", "文件数 / Files", "状态 / Status"],
    readyToImport: "可导入 / Ready",
    unresolved: "需要修正 / Needs review",
    demoCustodians: [
      { name: "John Doe", path: "/Doe, John", files: "12,480", status: "可导入 / Ready", tone: "success" },
      { name: "Dan Jones", path: "/Jones, Dan", files: "8,104", status: "可导入 / Ready", tone: "success" },
      { name: "Anna Smith", path: "/Smith, Anna", files: "3,218", status: "需要修正 / Needs review", tone: "warning" },
    ],
    selectedCustodians: "已选择 / Selected",
    editMapping: "修改匹配 / Edit mapping",
    destination: "目标文件夹 / Destination folder",
    destinationValue: "待选择 / Select destination",
    destinationOptions: ["待选择 / Select destination", "待审阅 / To review"],
    systemPanel: "系统已创建导入任务 / System-created import task",
    systemBatch: "后台批次 / Background batch",
    systemBatchValue: "已建立，用于统一记录本次导入的状态和报告。 / Created to track this import's status and reports.",
    systemSources: "来源项 / Source items",
    systemSourcesValue: "已按预览结果建立多个来源项，并分别关联 custodian。 / Multiple source items were created from the preview and linked to custodians.",
    systemNext: "下一步 / Next step",
    systemNextValue: "进入 Processing，运行 Inventory、Discover 或处理异常。 / Continue to Processing for Inventory, Discover, or exception handling.",
    systemNote: "这些是系统后台对象，不需要用户逐个创建。 / These are system objects; users do not create them one by one.",
    passwordNote: "加密文件密码在 Password Bank 中处理。 / Encrypted file passwords are managed in Password Bank.",
    validationPanel: "4. 提交导入 / 4. Submit import",
    validationText: "系统将在开始处理前检查文件路径、来源和必填配置。 / The system checks file paths, source, and required settings before Processing starts.",
    cancel: "取消 / Cancel",
    continue: "创建导入任务并进入 Processing / Create import task and continue to Processing",
    continueNotice: "已创建原始数据导入任务，下一步进入 Processing。 / Raw data import job created; next step is Processing.",
  },
  processing: {
    title: "处理 / Processing",
    subtitle: "Processing Source → Inventory → Discovery → Publish",
    ids: "REL-063–083, REL-394",
    createSource: "新建数据源 / New data source",
    processingSets: "处理集 / Processing Sets",
    sources: "数据源 / Data Sources",
    exceptions: "异常 / Exceptions",
    reports: "报告 / Reports",
    sourceName: "数据源名称 / Data source name",
    sourceNameValue: "董事邮箱补充批次 / Director mailbox supplement",
    sourceType: "输入方式 / Input method",
    rawFiles: "原始文件 / Raw files",
    structured: "结构化导入 / Structured import",
    uploadArea: "拖放文件到此处，或选择文件 / Drop files here, or choose files",
    uploadHint: "演示支持 PST、MSG、EML、PDF、DOCX、XLSX 和 ZIP / Demo accepts PST, MSG, EML, PDF, DOCX, XLSX, and ZIP",
    chooseFiles: "选择文件 / Choose files",
    profile: "处理配置 / Processing profile",
    profileValue: "中国项目默认配置 / China matter default",
    dedupe: "去重范围 / Deduplication scope",
    dedupeValue: "工作区级 / Workspace level",
    inventoryFirst: "先运行 Inventory / Run Inventory first",
    modalIntro: "本向导演示数据源创建，不会上传真实文件。 / This wizard demonstrates data-source creation and does not upload real files.",
    startUpload: "创建并开始上传 / Create & start upload",
    summary: [
      { label: "接收文件 / Received", value: "12,480" },
      { label: "发现项目 / Discovered", value: "18,226" },
      { label: "已发布 / Published", value: "11,946" },
      { label: "异常 / Exceptions", value: "17" },
    ],
    columns: ["处理集 / Processing Set", "阶段 / Stage", "进度 / Progress", "文档 / Documents", "异常 / Exceptions", "提交人 / Submitted by", "更新时间 / Updated"],
    rows: [
      { id: "PROC-2026-0918-04", name: "董事邮箱补充批次 / Director mailbox supplement", stage: "发布完成 / Published", progress: 100, docs: "528", exceptions: "4", owner: "王辰 / Chen Wang", updated: "今天 14:12 / Today 14:12", tone: "success" },
      { id: "PROC-2026-0917-02", name: "财务共享盘 / Finance shared drive", stage: "异常处理中 / Resolving exceptions", progress: 86, docs: "7,914", exceptions: "13", owner: "王辰 / Chen Wang", updated: "今天 13:48 / Today 13:48", tone: "warning" },
      { id: "PROC-2026-0915-01", name: "初始邮件批次 / Initial email set", stage: "发布完成 / Published", progress: 100, docs: "3,504", exceptions: "0", owner: "林然 / Ran Lin", updated: "9月18日 / Sep 18", tone: "success" },
    ],
    selectedTitle: "财务共享盘 / Finance shared drive",
    selectedStatus: "部分完成 / Partial completion",
    stages: [
      { order: "1", label: "上传 / Upload", status: "完成 / Complete", value: "4.8 GB" },
      { order: "2", label: "盘点 / Inventory", status: "完成 / Complete", value: "8,104 文件 / files" },
      { order: "3", label: "发现 / Discovery", status: "完成并有异常 / Complete with exceptions", value: "13 异常 / exceptions" },
      { order: "4", label: "发布 / Publish", status: "部分完成 / Partial", value: "7,914 文档 / documents" },
    ],
    exceptionTitle: "待处理异常 / Open exceptions",
    exceptionColumns: ["类型 / Type", "数量 / Count", "影响 / Impact", "建议操作 / Suggested action"],
    exceptionRows: [
      { type: "加密文件 / Encrypted files", count: "8", impact: "尚未发现内容 / Content not discovered", action: "添加密码并重试 / Add passwords & retry", tone: "warning" },
      { type: "文件损坏 / Corrupt files", count: "3", impact: "保留原件，无法预览 / Native retained, no preview", action: "下载并替换 / Download & replace", tone: "danger" },
      { type: "格式不支持 / Unsupported format", count: "2", impact: "未进入发布 / Not published", action: "查看文件清单 / View file list", tone: "neutral" },
    ],
    retrySuccess: "已将 8 个加密文件加入重试队列 / 8 encrypted files were queued for retry",
    createdSuccess: "已创建演示数据源并开始上传 / Demo data source created and upload started",
    directoryTitle: "Processing 工作流 / Processing workflow",
    directorySubtitle: "按官方处理顺序管理处理集、配置、数据源和处理结果。 / Manage processing sets, profiles, data sources, and results in the official processing order.",
    directoryStepsTitle: "操作顺序与进度 / Workflow and progress",
    directoryModulesTitle: "Processing 子模块 / Processing modules",
    directoryOpen: "进入模块 / Open module",
    directoryCurrent: "当前步骤 / Current step",
    directoryCompleted: "已完成 / Completed",
    directoryInProgress: "进行中 / In progress",
    directoryNotStarted: "未开始 / Not started",
    directoryWorkflow: [
      { order: "1", title: "创建处理集 / Create Processing Set", detail: "定义处理集名称和基础设置。 / Define the set name and basic settings.", status: "已完成 / Completed", tone: "success" },
      { order: "2", title: "添加处理配置 / Add Processing Profile", detail: "选择处理引擎使用的编号、发现、提取和发布设置。 / Select numbering, discovery, extraction, and publishing settings.", status: "已完成 / Completed", tone: "success" },
      { order: "3", title: "添加处理数据源 / Add Processing Data Source", detail: "指定源路径、保管人、目标文件夹和 OCR 语言。 / Specify source path, custodian, destination, and OCR languages.", status: "进行中 / In progress", tone: "warning" },
      { order: "4", title: "运行 Inventory / Run Inventory", detail: "盘点文件并在发现前筛选不需要的内容。 / Inventory files before discovery.", status: "未开始 / Not started", tone: "neutral" },
      { order: "5", title: "运行 Discover / Run Discover", detail: "提取内容并准备发布到工作区。 / Extract content and prepare it for publish.", status: "未开始 / Not started", tone: "neutral" },
      { order: "6", title: "检查报告与错误 / Review reports and errors", detail: "查看报告、作业错误、文件和替换文件。 / Review reports, job errors, files, and replacement files.", status: "未开始 / Not started", tone: "neutral" },
      { order: "7", title: "运行 Publish / Run Publish", detail: "将已发现内容发布到工作区。 / Publish discovered content to the workspace.", status: "未开始 / Not started", tone: "neutral" },
    ],
    directoryModules: [
      { id: "sets", title: "处理集 / Processing Sets", detail: "创建处理集、选择配置并查看处理阶段。 / Create sets, choose profiles, and monitor stages.", status: "进行中 / In progress", tone: "warning" },
      { id: "sources", title: "处理数据源 / Processing Data Sources", detail: "配置源路径、保管人、目标和 OCR 语言。 / Configure source paths, custodians, destinations, and OCR languages.", status: "未开始 / Not started", tone: "neutral" },
      { id: "profile", title: "处理配置 / Processing Profile", detail: "维护编号、Inventory、提取、去重和发布设置。 / Maintain numbering, inventory, extraction, deduplication, and publish settings.", status: "已完成 / Completed", tone: "success" },
      { id: "password", title: "密码库 | 处理 / Password Bank | Processing", detail: "管理加密文件处理所需的密码。 / Manage passwords required for encrypted files.", status: "未开始 / Not started", tone: "neutral" },
      { id: "inventory", title: "盘点 / Inventory", detail: "查看盘点任务和文件统计。 / Review inventory jobs and file counts.", status: "未开始 / Not started", tone: "neutral" },
      { id: "reports", title: "报告 / Reports", detail: "查看 Inventory、Discovery 和 Publish 报告。 / View inventory, discovery, and publish reports.", status: "未开始 / Not started", tone: "neutral" },
      { id: "errors", title: "作业错误 / Job Errors", detail: "集中查看和重试处理错误。 / Review and retry processing errors.", status: "有待处理项 / Action required", tone: "danger" },
      { id: "files", title: "文件 / Files", detail: "筛选和查看处理集中的文件。 / Filter and inspect files in a processing set.", status: "未开始 / Not started", tone: "neutral" },
      { id: "replacement", title: "替换文件 / Replacement Files", detail: "管理需要替换的原始文件。 / Manage native files that need replacement.", status: "未开始 / Not started", tone: "neutral" },
    ],
    backToDirectory: "返回 Processing 目录 / Back to Processing directory",
    sets: {
      title: "处理集 / Processing Sets",
      subtitle: "创建处理集并按 Inventory、Discover、Publish 顺序推进。 / Create sets and move through Inventory, Discover, and Publish.",
      newSet: "新建处理集 / New Processing Set",
      quickCreate: "快速创建处理集 / Quick Create Set(s)",
      allSets: "全部处理集 / All Processing Sets",
      search: "搜索处理集 / Search processing sets",
      newSetName: "新处理集 / New processing set",
      profileOptions: ["中国项目默认配置 / China matter default", "Default Update", "Standard Settings with Autopublish", "Updated Profile with No Autopublish"],
      emailRecipientsPlaceholder: "user@example.com; reviewer@example.com",
      timezoneOptions: ["(UTC-06:00) Central Time (US & Canada)", "(UTC+08:00) China Standard Time", "(UTC+00:00) Coordinated Universal Time"],
      orderValue: "0",
      zero: "0",
      zeroPercent: "0%",
      oneOfOne: "1 / 1",
      oneOfTwo: "1 / 2",
      columns: ["处理集 / Processing Set", "处理配置 / Processing Profile", "数据源 / Data Sources", "阶段 / Stage", "状态 / Status", "更新时间 / Updated"],
      basicSettings: "基本设置 / Basic Settings",
      statusDisplay: "处理集状态 / Processing Set Status",
      setName: "名称 / Name",
      profile: "处理配置 / Processing Profile",
      profileValue: "中国项目默认配置 / China matter default",
      addProfile: "添加 / Add",
      emailRecipients: "电子邮件通知收件人（用分号分隔） / Email notification recipients (separate by semi-colon)",
      saveSet: "保存处理集 / Save Processing Set",
      saved: "处理集已保存。 / Processing set saved.",
      dataSource: "处理数据源 / Processing Data Source",
      data: "数据 / Data",
      jobErrors: "作业错误 / Job Errors",
      inventoryOptional: "Inventory（可选） / Inventory (Optional)",
      discover: "Discover / Discovery",
      publish: "Publish / Publish",
      notStarted: "未开始 / Not Started",
      inventoryCount: "Inventory 数量 / Inventory count",
      discoverCount: "Discover 数量 / Discover count",
      publishCount: "Publish 数量 / Publish count",
      totalExceptions: "异常总数 / Total exceptions",
      processFiles: "处理文件 / Process Files",
      inventoryFiles: "Inventory 文件 / Inventory Files",
      filterFiles: "筛选文件 / Filter Files",
      discoverFiles: "Discover 文件 / Discover Files",
      retryFileExceptions: "重试文件异常 / Retry File Exceptions",
      publishFiles: "Publish 文件 / Publish Files",
      reports: "报告 / Reports",
      inventoryReport: "Inventory 报告 / Inventory Report",
      discoveryReport: "Discovery 报告 / Discovery Report",
      allReports: "全部报告 / All Reports",
      exceptions: "异常 / Exceptions",
      fileExceptions: "文件异常 / File Exceptions",
      dataSourceColumns: ["状态 / Status", "完成百分比 / Percent complete", "源路径 / Source path", "保管人 / Custodian", "文档编号 / Document numbering", "时区 / Time zone", "OCR 语言 / OCR language(s)"],
      noData: "暂无数据。 / No data.",
      createDataSource: "新建 / New",
      deleteDataSource: "删除 / Delete",
      sourcePath: "源路径 / Source path",
      browse: "浏览 / Browse",
      selectSourcePath: "选择处理源路径 / Select processing source path",
      sourceLocations: ["\\\\files\\processing\\finance\\", "\\\\files\\processing\\email\\", "\\\\files\\processing\\legal-hold\\"],
      sourceLocationHint: "处理服务账户必须拥有该 Processing Source Location 的读取权限。 / The Relativity Service Account must have read access to this Processing Source Location.",
      custodian: "保管人 / Custodian",
      selectCustodian: "选择保管人 / Select Custodian",
      addCustodian: "添加保管人 / Add Custodian",
      custodianType: "类型 / Type",
      person: "个人 / Person",
      other: "其他 / Other",
      firstName: "名 / First Name",
      lastName: "姓 / Last Name",
      fullName: "全名 / Full Name",
      classification: "分类 / Classification",
      custodianProcessing: "保管人 - 处理 / Custodian - Processing",
      communicator: "通信人 / Communicator",
      custodianNotes: "备注 / Notes",
      saveCustodian: "保存保管人 / Save Custodian",
      custodianRequired: "请选择或添加保管人。 / Select or add a custodian.",
      custodianOptions: ["Allen, Phillip / Allen, Phillip", "Chen, Wei / Chen, Wei", "Li, Ming / Li, Ming"],
      destinationFolder: "目标文件夹 / Destination folder",
      selectDestinationFolder: "选择目标文件夹 / Select destination folder",
      destinationFolders: ["\\Workspace Root", "\\Workspace Root\\Finance", "\\Workspace Root\\Email", "\\Workspace Root\\Legal Hold"],
      sourcePathRequired: "请选择源路径。 / Select a source path.",
      destinationRequired: "请选择目标文件夹。 / Select a destination folder.",
      timeZone: "时区 / Time zone",
      ocrLanguages: "OCR 语言 / OCR language(s)",
      numberingPrefix: "文档编号前缀 / Document numbering prefix",
      advancedOptions: "高级选项 / Advanced Options",
      sourceName: "名称 / Name",
      order: "顺序 / Order",
      select: "选择 / Select",
      clear: "清除 / Clear",
      add: "添加 / Add",
      sourcePathValue: "\\\\files\\processing\\finance\\",
      custodianValue: "Allen, Phillip / Allen, Phillip",
      destinationValue: "Allen, Phillip / Allen, Phillip",
      timezoneValue: "(UTC-06:00) Central Time (US & Canada)",
      ocrLanguageValue: "English\nFrench\nSpanish",
      numberingPrefixValue: "PAllen_",
      launchInventory: "开始 Inventory / Start Inventory",
      launchDiscover: "开始 Discover / Start Discover",
      launchPublish: "开始 Publish / Start Publish",
      actionSaved: "处理操作已加入队列。 / Processing action queued.",
      dataSourceSaved: "处理数据源已保存并关联到处理集。 / Processing data source saved and associated with the processing set.",
    },
    modulePlaceholder: {
      titleSuffix: "模块 / Module",
      subtitle: "该模块已加入 Processing 目录，后续可继续配置具体操作。 / This module is available from the Processing directory and can be configured next.",
      empty: "当前没有需要处理的演示记录。 / There are no demo records to process yet.",
    },
    settings: {
      title: "处理设置 / Processing Settings",
      subtitle: "为当前工作区配置处理集的编号、发现、提取、短消息转换、去重和发布行为。 / Configure numbering, discovery, extraction, short-message conversion, deduplication, and publishing for this workspace.",
      helpLabel: "查看设置说明 / View setting help",
      save: "保存处理设置 / Save processing settings",
      saved: "处理设置已保存到当前演示会话 / Processing settings saved to this demo session",
      select: "选择 / Select",
      yes: "是 / Yes",
      no: "否 / No",
      numbering: {
        title: "编号设置 / Numbering Settings",
        numberingType: "编号类型 * / Numbering Type *",
        numberingTypes: ["自动编号 / Auto Number", "定义起始编号 / Define Start Number", "分层编号 / Level Numbering"],
        defaultPrefix: "默认文档编号前缀 * / Default document numbering prefix *",
        numberOfDigits: "数字位数（用零填充） * / Number of digits (padded with zeros) *",
        digitOptions: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
        parentChild: "父子编号 * / Parent/Child Numbering *",
        parentChildOptions: ["始终添加后缀 / Suffix Always", "始终连续 / Continuous Always", "连续，重试时添加后缀 / Continuous, Suffix on Retry"],
        delimiter: "分隔符 * / Delimiter *",
        delimiterOptions: [".（句点） / . (period)", "-（连字符） / - (hyphen)", "_（下划线） / _ (underscore)"],
      },
      inventory: {
        title: "Inventory｜Discovery 设置 / Inventory | Discover Settings",
        denistSettings: "DeNIST 设置 / DeNIST Settings",
        denist: "DeNIST * / DeNIST *",
        denistMode: "DeNIST 模式 / DeNIST Mode",
        denistModes: ["DeNIST 所有文件 / DeNIST all files", "不拆分父子组 / Do not break parent/child groups"],
        defaultCustodian: "默认保管人设置 / Default Custodian Settings",
        ocrLanguages: "默认 OCR 语言 * / Default OCR languages *",
        ocrLanguageOptions: ["English / 英语", "Chinese Simplified / 简体中文", "Japanese / 日语"],
        add: "添加 / Add",
        timezone: "默认时区 * / Default time zone *",
        timezoneOptions: ["UTC+08:00 / China Standard Time", "UTC+00:00 / Coordinated Universal Time", "UTC-05:00 / Eastern Time"],
        inclusion: "包含／排除文件列表 / Inclusion/Exclusion File List",
        includeExclude: "包含／排除 * / Include/Exclude *",
        mode: "模式 * / Mode *",
        modes: ["全部文件 / All Files", "不拆分父子组 / Do not break parent/child groups"],
        fileExtensions: "文件扩展名 * / File Extensions *",
        fileExtensionsValue: ".pst\n.msg\n.eml",
        required: "（必填）* / (required) *",
        inclusionOptions: ["包含 / Inclusion", "排除 / Exclusion"],
      },
      extraction: {
        title: "提取设置 / Extraction Settings",
        extractChildren: "提取子项 * / Extract children *",
        doNotExtract: "提取子项时不提取 / When extracting children, do not extract",
        embeddedImages: "MS Office 嵌入图像 / MS Office embedded images",
        embeddedObjects: "MS Office 嵌入对象 / MS Office embedded objects",
        emailInlineImages: "电子邮件内嵌图像 / Email inline images",
        rollUpImageText: "汇总图像文本 / Roll up image text",
        emailOutput: "电子邮件输出 * / Email Output *",
        emailOutputOptions: ["MSG / MSG", "MHT / MHT"],
        choose: "选择... / Choose...",
        textExtraction: "Excel 文本提取方法 * / Excel Text Extraction Method *",
        powerpointExtraction: "PowerPoint 文本提取方法 * / PowerPoint Text Extraction Method *",
        wordExtraction: "Word 文本提取方法 * / Word Text Extraction Method *",
        textExtractionOptions: [
          "Relativity（推荐） / Relativity (Recommended)",
          "Native（旧版） / Native (Legacy)",
          "Native - failover to dtSearch（旧版） / Native - failover to dtSearch (Legacy)",
          "dtSearch - failover to Native（旧版） / dtSearch - failover to Native (Legacy)",
        ],
        headerFooter: "Excel 页眉／页脚提取 * / Excel Header/Footer Extraction *",
        headerFooterOptions: ["不提取 / Do not extract", "提取并置于末尾 / Extract and place at end", "提取并内联（减慢文本提取） / Extract and place inline (slows text extraction)"],
        ocr: "OCR * / OCR *",
        enabledDisabled: ["启用 / Enabled", "禁用 / Disabled"],
        ocrAccuracy: "OCR 准确率 / OCR Accuracy",
        accuracyOptions: ["选择... / Choose...", "高（最慢速度） / High (Slowest Speed)", "中（平均速度） / Medium (Average Speed)", "低（最快速度） / Low (Fastest Speed)"],
        ocrSeparator: "OCR 文本分隔符 / OCR Text Separator",
      },
      shortMessage: {
        title: "短消息转换设置 / Short Message Conversion Settings",
        sliceBy: "切片依据 * / Slice by *",
        sliceOptions: ["4 小时 / 4 hours", "8 小时 / 8 hours", "12 小时 / 12 hours", "24 小时 / 24 hours", "1 周 / 1 week"],
        slack: "Slack",
        downloadAttachments: "下载附件 / Download attachments",
        teams: "Teams",
        cellebrite: "Cellebrite",
        import: "导入 / Import",
        importOptions: ["短信／彩信 / SMS / MMS", "聊天应用 / Chat apps", "媒体文件 / Media files", "电子邮件 / Email", "其他（日志和位置） / Other (logs and locations)"],
      },
      deduplication: {
        title: "去重设置 / Deduplication Settings",
        method: "去重方法 * / Deduplication method *",
        methodOptions: ["无 / None", "全局 / Global", "按保管人 / Custodial"],
        propagate: "传播去重数据 * / Propagate deduplication data *",
      },
      publish: {
        title: "发布设置 / Publish Settings",
        autoPublish: "自动发布 / Auto Publish",
        autoPublishSet: "设置自动发布 * / Auto-publish set *",
        destinationStructure: "默认目标文件夹结构 / Default Destination Folder Structure",
        destinationFolder: "默认目标文件夹 * / Default destination folder *",
        destinationOptions: ["选择 / Select", "按保管人 / By custodian", "按源文件夹 / By source folder"],
        useSource: "是否使用源文件夹结构 * / Do you want to use source folder structure *",
        select: "选择 / Select",
      },
    },
  },
  documents: {
    title: "文档 / Documents",
    subtitle: "筛选、搜索、保存结果并进入审阅 / Filter, search, save results, and open review",
    ids: "REL-116, REL-135–148, REL-386–387",
    allDocuments: "全部文档 / All Documents",
    savedSearches: "保存的搜索 / Saved Searches",
    folders: "文件夹 / Folders",
    folderItems: ["全部文档 / All Documents", "需一审 / First Pass", "合同与附件 / Contracts & Attachments", "遮盖候选 / Redaction Candidates", "待制作 / Production Candidates"],
    conditions: "搜索条件 / Search Conditions",
    conditionNumber: "1",
    addCondition: "添加条件 / Add Condition",
    runSearch: "运行搜索 / Run Search",
    autoRun: "自动运行 / Auto Run",
    conditionField: "字段 / Field",
    conditionFieldValue: "全文 / Extracted Text",
    conditionOperator: "运算符 / Operator",
    conditionOperatorValue: "包含 / Contains",
    conditionValue: "关键词或短语 / Keyword or phrase",
    searchValue: "termination agreement",
    indexCoverage: "索引覆盖 10,932 / 11,946 文档 / Indexed 10,932 of 11,946 documents",
    saveSearch: "保存搜索 / Save Search",
    savedSearchName: "搜索名称 / Search name",
    savedSearchNameValue: "First Pass - Termination Agreements",
    saveSearchSuccess: "搜索已保存 / Search saved",
    bulkEdit: "批量编辑 / Mass Edit",
    includeFamily: "包括家族 / Include Family",
    directHit: "直接命中 / Direct hit",
    familyHit: "家族扩展 / Family expansion",
    resultCount: "找到 7 个结果，其中 2 个来自家族扩展 / 7 results, including 2 from family expansion",
    columns: ["", "控制编号 / Control Number", "文件名 / File name", "记录类型 / Record Type", "响应性 / Responsiveness", "保密性 / Confidentiality", "关系 / Relation"],
    docs: [
      { id: "REL00010328", file: "Termination_Agreement_Draft.docx", type: "Microsoft Word", responsive: "响应 / Responsive", confidential: "保密 / Confidential", relation: "父件 / Parent", direct: true, locked: false },
      { id: "REL00010329", file: "Appendix_A_Pricing.xlsx", type: "Microsoft Excel", responsive: "响应 / Responsive", confidential: "保密 / Confidential", relation: "附件 / Attachment", direct: false, locked: false },
      { id: "REL00010330", file: "FW_Termination_timeline.msg", type: "Email", responsive: "待审阅 / Not Reviewed", confidential: "未设置 / Not Set", relation: "邮件链 / Email Thread", direct: true, locked: false },
      { id: "REL00010331", file: "Board_minutes_2025-03.pdf", type: "PDF", responsive: "待审阅 / Not Reviewed", confidential: "未设置 / Not Set", relation: "独立 / Standalone", direct: true, locked: true },
      { id: "REL00010332", file: "Termination_Agreement_Final.pdf", type: "PDF", responsive: "响应 / Responsive", confidential: "保密 / Confidential", relation: "近重复 / Near Duplicate", direct: true, locked: false },
      { id: "REL00010333", file: "Legal_comments.msg", type: "Email", responsive: "不响应 / Not Responsive", confidential: "特权 / Privileged", relation: "父件 / Parent", direct: true, locked: false },
      { id: "REL00010334", file: "Counsel_Memo.pdf", type: "PDF", responsive: "不响应 / Not Responsive", confidential: "特权 / Privileged", relation: "附件 / Attachment", direct: false, locked: false },
    ],
    lockedMessage: "该文档正由周宁审阅，请稍后重试 / This document is checked out by Ning Zhou; try again later",
    openReview: "在 Viewer 中打开 / Open in Viewer",
  },
  analytics: {
    title: "搜索与分析 / Search & Analytics",
    subtitle: "索引、邮件链、近重复与语言识别 / Indexes, email threads, near duplicates, and language identification",
    ids: "REL-084–101, REL-135–143, REL-148, REL-372–373",
    indexes: "搜索索引 / Search Indexes",
    structured: "结构化分析 / Structured Analytics",
    communication: "通信分析 / Communication Analysis",
    indexName: "dtSearch - Morninglight",
    indexStatus: "活动 / Active",
    indexCoverage: "10,932 / 11,946 文档 / documents",
    indexUpdated: "最后增量构建：今天 14:18 / Last incremental build: Today 14:18",
    incremental: "运行增量构建 / Run incremental build",
    rebuild: "完整重建 / Full rebuild",
    running: "正在构建索引 / Building index",
    runningDetail: "用户仍可搜索已索引的 10,932 份文档。 / Users can continue searching the 10,932 indexed documents.",
    runningProgress: 64,
    runSuccess: "增量索引任务已进入队列 / Incremental index job queued",
    analysisSets: "分析集 / Analysis Sets",
    newAnalysis: "新建分析集 / New analysis set",
    columns: ["分析集 / Analysis Set", "类型 / Type", "范围 / Scope", "状态 / Status", "结果 / Results", "更新时间 / Updated"],
    rows: [
      { name: "邮件主题与重复 / Email threads & duplicates", type: "邮件链 + 近重复 / Email Threading + TND", scope: "10,432", status: "完成 / Complete", result: "2,184 邮件链 / threads", updated: "今天 11:06 / Today 11:06", tone: "success" },
      { name: "语言识别 / Language identification", type: "语言 / Language", scope: "11,946", status: "完成 / Complete", result: "8 种语言 / languages", updated: "9月20日 / Sep 20", tone: "success" },
      { name: "合同概念聚类 / Contract concept clusters", type: "聚类 / Clustering", scope: "4,281", status: "部分完成 / Partial", result: "38 聚类 / clusters", updated: "9月20日 / Sep 20", tone: "warning" },
    ],
    threadTitle: "邮件链概览 / Email Thread Overview",
    threadStats: [
      { label: "邮件链 / Threads", value: "2,184" },
      { label: "可包含消息 / Inclusive emails", value: "3,912" },
      { label: "近重复组 / Near-duplicate groups", value: "604" },
      { label: "识别人物 / Normalized people", value: "328" },
    ],
    languageTitle: "语言分布 / Language Distribution",
    languages: [
      { label: "英语 / English", value: 62, count: "7,407" },
      { label: "简体中文 / Simplified Chinese", value: 28, count: "3,345" },
      { label: "繁体中文 / Traditional Chinese", value: 6, count: "717" },
      { label: "其他 / Other", value: 4, count: "477" },
    ],
    boundary: "Family、Email Thread 与 Near Duplicate 是不同关系，结果分别呈现。 / Family, Email Thread, and Near Duplicate are distinct relationships and are shown separately.",
  },
  review: {
    title: "审阅 / Review",
    subtitle: "Viewer、文档内搜索、编码与 Save & Next",
    ids: "REL-117–134, REL-144–145, REL-379–380, REL-386–387",
    queue: "一审优先队列 / First Pass Priority Queue",
    queueStatus: "活动 / Active",
    queueProgress: "2,914 / 4,280 已完成 / completed",
    returnQueue: "返回队列 / Return to queue",
    documentList: "文档列表 / Document list",
    viewerTabs: ["原生 / Native", "图像 / Image", "提取文本 / Extracted Text", "PDF / PDF"],
    findDocument: "文档内查找 / Find in document",
    findValue: "termination",
    hits: "3 个命中 / 3 hits",
    related: "相关项 / Related Items",
    family: "家族 / Family",
    emailThread: "邮件链 / Email Thread",
    nearDuplicate: "近重复 / Near Duplicate",
    history: "历史 / History",
    documentTitle: "Termination Agreement - Draft",
    documentMeta: "REL00010328 · Microsoft Word · 8 页 / pages",
    pageCount: "第 1 页，共 8 页 / Page 1 of 8",
    paperTitle: "TERMINATION AGREEMENT",
    paperSubtitle: "终止协议 / Termination Agreement",
    paperIntro: "This Termination Agreement is entered into as of March 14, 2025, by and between Northstar Holdings Ltd. and Morninglight Technology Co., Ltd.",
    paperSection: "1. Termination / 终止",
    paperBody: "The parties agree to terminate the Services Agreement. All confidential materials must be returned within thirty (30) days. The final payment schedule is attached as Appendix A.",
    paperConfidential: "CONFIDENTIAL - ATTORNEYS' EYES ONLY / 保密 - 仅限律师查看",
    coding: "编码面板 / Coding Panel",
    responsiveness: "响应性 / Responsiveness",
    responsivenessOptions: ["响应 / Responsive", "不响应 / Not Responsive", "需要进一步审阅 / Needs Further Review"],
    confidentiality: "保密性 / Confidentiality",
    confidentialityOptions: ["非保密 / Not Confidential", "保密 / Confidential", "特权 / Privileged"],
    issueTags: "问题标签 / Issue Tags",
    issueOptions: ["合同终止 / Contract Termination", "定价 / Pricing", "法律意见 / Legal Advice", "人员决策 / Personnel Decision"],
    notes: "审阅备注 / Review notes",
    notesPlaceholder: "输入仅供团队查看的备注 / Enter a team-only note",
    required: "必填 / Required",
    saved: "编码已保存，已进入下一份文档 / Coding saved; moved to next document",
    validation: "请完成响应性与保密性字段 / Complete Responsiveness and Confidentiality",
    copyPrevious: "复制上一份 / Copy previous",
    zoomIn: "放大 / Zoom in",
    zoomOut: "缩小 / Zoom out",
    rotate: "旋转 / Rotate",
    fullScreen: "全屏 / Full screen",
    documentItems: [
      { id: "REL00010328", label: "Termination Agreement", state: "当前 / Current", locked: false },
      { id: "REL00010330", label: "FW: Termination timeline", state: "未审阅 / Not reviewed", locked: false },
      { id: "REL00010331", label: "Board minutes", state: "周宁占用 / Locked by Ning", locked: true },
      { id: "REL00010332", label: "Termination Final", state: "未审阅 / Not reviewed", locked: false },
    ],
  },
  redaction: {
    title: "成像与遮盖 / Imaging & Redact",
    subtitle: "OCR、标记集、手工遮盖与多表示泄漏检查 / OCR, markup sets, manual redactions, and cross-representation leak checks",
    ids: "REL-149–178, REL-390",
    queue: "遮盖复核队列 / Redaction QC Queue",
    documentMeta: "REL00010342 · Employee_Settlement.pdf · 4 页 / pages",
    markupSet: "标记集 / Markup Set",
    markupSetValue: "敏感个人信息 / Personal Sensitive Data",
    reason: "遮盖原因 / Redaction Reason",
    reasonValue: "个人身份信息 / Personally Identifiable Information",
    tools: "遮盖工具 / Redaction Tools",
    rectangle: "矩形遮盖 / Rectangle redaction",
    fullPage: "整页遮盖 / Full-page redaction",
    text: "文本遮盖 / Text redaction",
    inverse: "反向遮盖 / Inverse redaction",
    applyDemo: "添加示例遮盖 / Add sample redaction",
    removeDemo: "移除示例遮盖 / Remove sample redaction",
    pageCount: "第 2 页，共 4 页 / Page 2 of 4",
    paperTitle: "EMPLOYEE SETTLEMENT SUMMARY",
    paperSubtitle: "员工和解摘要 / Employee Settlement Summary",
    employee: "Employee / 员工: Mei Zhang",
    address: "Address / 地址: 88 Huaxia Road, Shanghai",
    identity: "National ID / 身份证号: 310101199001012345",
    bank: "Bank account / 银行账户: 6222 0000 1234 5678",
    body: "The parties agree that the settlement amount and related terms remain confidential. Payment will be made within ten business days.",
    qc: "质检检查 / Quality Checks",
    qcItems: [
      { id: "image", label: "图像层已遮盖 / Image layer redacted", state: "通过 / Pass" },
      { id: "ocr", label: "OCR 文本层无残留 / OCR text layer clean", state: "失败 / Fail" },
      { id: "native", label: "Native 输出已排除 / Native output excluded", state: "通过 / Pass" },
      { id: "metadata", label: "元数据无敏感值 / Metadata contains no sensitive values", state: "待确认 / Pending" },
    ],
    runLeakCheck: "运行泄漏检查 / Run leak check",
    leakCheckRunning: "正在检查图像、OCR 文本、Native 与元数据 / Checking image, OCR text, native, and metadata",
    leakCheckSuccess: "泄漏检查通过，可以提交复核 / Leak check passed; ready for QC submission",
    submitQc: "提交复核 / Submit for QC",
    approve: "接受 / Accept",
    reject: "拒绝 / Reject",
    blocked: "OCR 文本层仍包含被遮盖内容，不能提交 / Redacted content remains in the OCR text layer; submission is blocked",
    submitted: "遮盖已提交复核 / Redactions submitted for QC",
    draftStatus: "草稿 / Draft",
    pendingStatus: "待复核 / Pending QC",
  },
  production: {
    title: "制作与导出 / Production & Export",
    subtitle: "固定范围、编号、表示版本、校验与交付清单 / Fixed scope, numbering, representations, validation, and delivery manifest",
    ids: "REL-179–192, REL-394",
    productionSet: "制作集 / Production Set",
    productionName: "晨光项目第一次制作 / Morninglight First Production",
    statusDraft: "草稿 / Draft",
    steps: ["1 范围 / Scope", "2 编号 / Branding", "3 输出 / Output", "4 校验 / Validate", "5 运行 / Run"],
    source: "文档来源 / Document source",
    sourceValue: "保存的搜索：Production Candidates / Saved Search: Production Candidates",
    fixedCount: "固定范围 1,248 份文档 / Fixed scope: 1,248 documents",
    numbering: "编号 / Bates numbering",
    prefix: "前缀 / Prefix",
    prefixValue: "MLP",
    startNumber: "起始编号 / Start number",
    startNumberValue: "000001",
    padding: "位数 / Digits",
    paddingValue: "6",
    output: "输出表示 / Output representations",
    outputOptions: [
      { id: "image", label: "单页 TIFF 图像 / Single-page TIFF images", checked: true },
      { id: "text", label: "提取文本 / Extracted text", checked: true },
      { id: "native", label: "符合条件的 Native / Eligible natives", checked: false },
      { id: "pdf", label: "合并 PDF / Combined PDF", checked: false },
      { id: "load", label: "DAT + Opticon load files / DAT + Opticon load files", checked: true },
    ],
    redactionSet: "使用的遮盖标记集 / Redaction markup set",
    redactionSetValue: "敏感个人信息 - 已接受 / Personal Sensitive Data - Accepted",
    placeholder: "占位页文字 / Placeholder text",
    placeholderValue: "DOCUMENT WITHHELD - PRIVILEGED / 文档因特权不予提供",
    runValidation: "运行制作前校验 / Run pre-production validation",
    validationTitle: "校验结果 / Validation Results",
    validationSummary: "1,248 份文档中有 3 项阻断问题 / 3 blocking issues across 1,248 documents",
    validationRows: [
      { check: "遮盖复核 / Redaction QC", result: "3 份未通过 / 3 failed", severity: "阻断 / Blocking", tone: "danger" },
      { check: "编号连续性 / Bates continuity", result: "通过 / Passed", severity: "正常 / Clear", tone: "success" },
      { check: "文件表示 / File representations", result: "通过 / Passed", severity: "正常 / Clear", tone: "success" },
      { check: "必填字段 / Required fields", result: "2 个警告 / 2 warnings", severity: "可继续 / Can proceed", tone: "warning" },
    ],
    resolveRedaction: "去处理遮盖问题 / Resolve redaction issues",
    rerunValidation: "重新校验 / Re-run validation",
    validationSuccess: "制作前校验已通过 / Pre-production validation passed",
    runProduction: "运行制作 / Run production",
    blocked: "存在阻断问题，不能运行制作 / Production cannot run while blocking issues remain",
    running: "制作运行中 / Production running",
    runningDetail: "正在生成图像、文本与 load files / Generating images, text, and load files",
    completed: "制作完成 / Production complete",
    completedDetail: "1,248 份文档 · 3.6 GB · MLP000001–MLP003842 / 1,248 documents · 3.6 GB · MLP000001–MLP003842",
    manifest: "下载交付清单 / Download delivery manifest",
    package: "下载制作包 / Download production package",
  },
  tasks: {
    title: "任务中心 / Task Center",
    subtitle: "跨工作区查看后台任务、错误和重试 / Monitor background jobs, errors, and retries across the workspace",
    ids: "REL-077–080, REL-149–163, REL-179–192, REL-372–373",
    filters: ["全部 / All", "运行中 / Running", "已完成 / Completed", "需要处理 / Needs action"],
    columns: ["任务 / Task", "对象 / Object", "状态 / Status", "进度 / Progress", "发起人 / Started by", "开始时间 / Started", "耗时 / Duration"],
    rows: [
      { task: "增量索引 / Incremental index", object: "dtSearch - Morninglight", status: "运行中 / Running", progress: 64, owner: "林然 / Ran Lin", started: "15:04", duration: "6 分钟 / min", tone: "info" },
      { task: "处理异常重试 / Processing exception retry", object: "PROC-2026-0917-02", status: "排队 / Queued", progress: 0, owner: "王辰 / Chen Wang", started: "15:08", duration: "—", tone: "neutral" },
      { task: "OCR 集 / OCR Set", object: "扫描合同补充 / Scanned contract supplement", status: "已完成 / Completed", progress: 100, owner: "系统 / System", started: "14:20", duration: "28 分钟 / min", tone: "success" },
      { task: "分析集 / Analytics Set", object: "合同概念聚类 / Contract concept clusters", status: "部分完成 / Partial", progress: 82, owner: "林然 / Ran Lin", started: "昨天 / Yesterday", duration: "47 分钟 / min", tone: "warning" },
      { task: "制作校验 / Production validation", object: "Morninglight First Production", status: "需要处理 / Needs action", progress: 100, owner: "林然 / Ran Lin", started: "14:58", duration: "2 分钟 / min", tone: "danger" },
    ],
    detailTitle: "任务详情 / Task Details",
    logTitle: "运行记录 / Run log",
    log: [
      "15:04:12 · 已创建增量构建 / Incremental build created",
      "15:04:18 · 已锁定索引配置 / Index configuration locked",
      "15:05:02 · 已处理 6,842 / 10,932 文档 / documents processed",
      "15:10:26 · 当前吞吐 720 文档/分钟 / Current throughput: 720 docs/min",
    ],
  },
  overlays: {
    notificationTitle: "通知 / Notifications",
    notifications: [
      { title: "遮盖泄漏检查失败 / Redaction leak check failed", detail: "REL00010342 · 3 分钟前 / 3 min ago", tone: "danger" },
      { title: "索引任务已开始 / Index job started", detail: "dtSearch - Morninglight · 8 分钟前 / 8 min ago", tone: "info" },
      { title: "处理异常已重试 / Processing exceptions retried", detail: "8 个文件 / files · 12 分钟前 / 12 min ago", tone: "success" },
    ],
    userTitle: "用户选项 / User Options",
    userItems: ["个人资料 / Profile", "界面偏好 / Preferences", "键盘快捷键 / Keyboard shortcuts", "退出 / Sign out"],
    helpTitle: "原型说明 / Prototype Help",
    helpText: "使用左侧导航体验完整流程。带 P0/P1 标签和 REL 编号的区域可追溯到当前优先级功能清单。 / Use the left navigation to explore the end-to-end flow. P0/P1 badges and REL IDs trace back to the current prioritized feature list.",
    noBackend: "这是可交互的前端原型，操作只改变当前浏览器中的演示状态。 / This is an interactive front-end prototype; actions only change demo state in this browser session.",
  },
  toasts: {
    generic: "操作已完成 / Action completed",
    copied: "已复制 / Copied",
    download: "演示文件已准备 / Demo file is ready",
  },
} as const;

export type PageId = (typeof copy.navigation)[number]["id"];
