import { useState } from "react";
import { copy } from "../constants/copy";
import type { FieldRecord } from "../state/fields";
import type { LayoutRecord } from "../state/layouts";
import { sortedItems } from "../state/layouts";
import { Button, Panel } from "./UI";
const t = copy.layoutManagement;
export function LayoutPreview({ layout, fields, onClose }: { layout: LayoutRecord; fields: FieldRecord[]; onClose: () => void }) {
  const [document, setDocument] = useState<string>(t.previewDocuments[0]), [values, setValues] = useState<Record<string, string>>({}), [copied, setCopied] = useState(false);
  const set = (id: string, value: string) => setValues(current => ({ ...current, [id]: value }));
  return <div className="layout-preview" role="dialog" aria-modal="true" aria-label={t.preview}><header className="layout-builder__header"><strong>{t.preview}{t.separator}{layout.name}</strong><Button onClick={onClose}>{copy.common.close}</Button></header><div className="layout-preview__toolbar"><label>{t.previewDocument}<select aria-label={t.previewDocument} value={document} onChange={e => { setDocument(e.target.value); setCopied(false); }}>{t.previewDocuments.map(id => <option key={id}>{id}</option>)}</select></label>{layout.copyPrevious && <Button onClick={() => { setValues(current => ({ ...current, ...Object.fromEntries(layout.sections.flatMap(section => section.items.filter(item => item.allowCopy).map(item => [item.fieldId, current[item.fieldId] || "已复制"]))) })); setCopied(true); }}>{t.previousCopy}</Button>}{copied && <span className="badge badge--success">{t.copied}</span>}</div><main className="layout-preview__body">{layout.sections.map(section => <Panel key={section.id} title={section.name}>{section.help && <div className="layout-help" dangerouslySetInnerHTML={{ __html: section.help }} />}{sortedItems(section.items).map(item => { const field = fields.find(candidate => candidate.id === item.fieldId); if (!field) return null; const label = item.customLabel || field.name; return <label className="preview-field" key={item.id}><span>{item.showName ? label : ""}</span>{item.display === "checkbox" ? <select aria-label={label} multiple value={values[item.fieldId] ? [values[item.fieldId]] : []} onChange={e => set(item.fieldId, Array.from(e.target.selectedOptions).map(option => option.value).join(", "))}>{field.choices.map(choice => <option key={choice.id} value={choice.name}>{choice.name}</option>)}</select> : <input aria-label={label} disabled={item.readOnly} value={values[item.fieldId] ?? ""} onChange={e => set(item.fieldId, e.target.value)} />}</label>; })}</Panel>)}</main></div>;
}
